---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)

options(scipen=999)  # turn-off scientific notation like 1e+48

library(tidyverse)
library (rtweet)

```

## Ingest Text


```{r, echo=FALSE}

# whatever name you assigned to your created app
appname <- "JBatUN-Racism-Study"

## api key (example below is not a real key)
key <- "kRMpaaYqZk5aoRKaWYQDVRfC1"

## api secret (example below is not a real key)
secret <- "9CmL7q5bi0L9Q2a6tMtgaCU1wDANTKkCgf9z9qitp82yPGEUY8"

twitter_token <- create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret,
  set_renv = TRUE)


```


```{r}

#unitednations 
#humanrights 
#peace 
#sdg 
#sustainability
#socialimpact
#humanitarian 
#climatechange

#reuters

keyword <- "unitednations"
file <- paste0("search-tweets-", keyword, ".csv")

search <- search_tweets(keyword, n=1000, include_rts=FALSE, lang="en", retryonratelimit = TRUE)

head(search)

write_as_csv(search, file, prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")


```



## Create Corpus


```{r}

corpus_csv <- read.csv(file, header = TRUE, stringsAsFactors = TRUE)

colnames_df <- data.frame(colnames(corpus_csv))
colnames_df$rid <- as.numeric(rownames(colnames_df))
colnames_df

text <- corpus_csv$text
rid <- as.numeric(rownames(corpus_csv))

save_csv <- data.frame(rid, text)

write.csv(save_csv, file , row.names = FALSE)

```


## Clean Corpus

```{r}

corpus_csv <- read.csv(file, header = TRUE, stringsAsFactors = TRUE)

```

