---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    #code_folding: show
    include:
     in_header: "../../../z-assemblers/fragments/header.html"
     after_body: "../../../z-assemblers/fragments/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48


library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS  
</div>

# Box and Whisker Plot
## Depict Variation in Data by Quartiles

Box and Whisker Plots (or simply boxplots) are very useful plots in descriptive statistics to analyze groups of numerical data through a five-number statistical summary. Box and whisker plots help you to see the variance of data as well as potential unusual data points in a dataset called outliers. The box-plot is especially useful for indicating whether a distribution is skewed and for comparing between two sets of numerical data.


The five statistics summary that a box-whisker plot portray are:

* __Minimum Value__ : The smallest value in the data set
* __Second quartile(Q1)__ : The value below which the lower 25% of the data are contained
* __Median value__ : The middle number in a range of numbers
* __Third quartile(Q3)__ : The value above which the upper 25% of the data are contained
* __Maximum value__ : The largest value in the data set


If outliers are present, the whisker on the appropriate side is drawn to 1.5 * IQR rather than the data minimum or the data maximum. This way, outliers are not calculated into the statistics of the dataset and would not be recognized as the minimum/maximum. Small circles or unfilled dots are drawn on the chart to indicate where suspected outliers lie.



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

