---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(maps)
library(geojsonio)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(tidyverse)
library(ggiraph)

```

<div class="activity">
MAPS  
</div>

***

# Section
## Subsection

```{r, echo=FALSE}

# Load data
coal_mines = read.csv("archetypes/global-energy-monitor/global-coal-mine-tracker-data.csv", header = TRUE, stringsAsFactors = FALSE)
coal_mines


```

```{r, message=FALSE, warning=FALSE, echo=FALSE, fig.width=10.5, fig.height=7.5}

# PLOT NATURAL EARTH BORDERS
ne_world <- ne_countries(scale = "medium", returnclass = "sf")
# class(ne_world)

# removes Antarctica
ne_world <- filter(ne_world, iso_a3 != "ATA")

# theme parameters
theme_opts <- theme(
  legend.position = "bottom",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

# color palette to use
pal <- wes_palette("Zissou1", 10, type = "continuous")

v1 <- ggplot(data = ne_world) +
  # map feature styling
  geom_sf(fill="white", color="#888888", stroke=0.5) +
  # bubble parameters
  geom_point( data = df, aes(x=lng, y=lat), size=2.0, color="black", alpha=0.8) +
  # size scaling applied to bubbles
  scale_size_continuous(range=c(1,12)) +
  scale_fill_gradientn(colours = pal) + 
  scale_color_gradientn(colours = pal) + 
  theme_bw() +
  labs(x="Longitude",
       y="Latitude",
       title = "Bubble Map", 
       subtitle="Top 10000 Cities of the World") +
  theme_opts

v1

```

```{r, echo=FALSE}

# ggsave(filename = "world-pm25.svg", plot = v1, width=11, height=6)

```



# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case


```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

