---
pagetitle: "The Red List"
output:
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: ["../../../z-assemblers/fragments/google-analytics.html", "../../../z-assemblers/fragments/header.html"]
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(dplyr)
library(purrr)
library(tidygraph)
library(ggraph)


```

<div class="activity">
GRAPHS
</div>

## Template

Source:  template

***

# Section
## Subsection

```{r, echo=FALSE}

df_taxonomy <- read.csv("archetypes/the-red-list/taxonomy.csv", header = TRUE, stringsAsFactors = FALSE)
df_taxonomy

df_assessments <- read.csv("archetypes/the-red-list/assessments.csv", header = TRUE, stringsAsFactors = FALSE)
df_assessments

```


# Section
## Subsection


```{r}

df_scientific_family <- df_taxonomy %>% select(scientificName, familyName)
names(df_scientific_family) <- c("from", "to")

df_family_order <- df_taxonomy %>% select(familyName, orderName)
names(df_family_order) <- c("from", "to")

df_order_class <- df_taxonomy %>% select(orderName, className)
names(df_order_class) <- c("from", "to")

df_class_phylum <- df_taxonomy %>% select(className, phylumName)
names(df_class_phylum) <- c("from", "to")

df_phylum_kingdom <- df_taxonomy %>% select(phylumName, kingdomName)
names(df_phylum_kingdom) <- c("from", "to")

df_edges <- rbind(df_scientific_family, df_family_order, df_order_class, df_class_phylum, df_phylum_kingdom)

```


### Prepare data [Wrangle]
#### Format the data into a graph data frame 


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Convert data to graph data frame
# directed FALSE means no flow. It's just an association
df_graph <- graph_from_data_frame( df_edges ) # , vertices=df_nodes

```


## Layout & Aesthetic Parameters
### Choose the types of Edges you would like to display


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Layouts can be computationally intensive
# Un-comment only for use

# igraph
# dh <- create_layout(cg, layout = 'dh')
# fr <- create_layout(cg, layout = 'fr')
# gem <- create_layout(cg, layout = 'gem')
# lgl <- create_layout(cg, layout = 'lgl')
sugiyama <- create_layout(df_graph, layout = 'sugiyama')
# star <- create_layout(cg, layout = 'star')
# kk <- create_layout(cg, layout = 'kk', maxiter = 100)
# drl <- create_layout(cg, layout = 'drl')
# linear_straight <- create_layout(cg, layout = 'linear')
# linear_circular <- create_layout(cg, layout = 'linear' , circular = TRUE)

# ggraph
# arc <- create_layout(cg, layout = 'linear')
# arc_circular <- create_layout(cg, layout = 'linear', circular = TRUE)
# stress <- create_layout(cg, layout = 'stress')
# sparse_stress <- create_layout(cg, layout = 'sparse_stress')
# backbone <- create_layout(cg, layout = 'backbone')
# pmds <- create_layout(cg, layout = 'pmds')
# eigen <- create_layout(cg, layout = 'eigen')
# centrality <- create_layout(cg, layout = 'centrality')
# focus <- create_layout(cg, layout = 'focus')
# dendrogram <- create_layout(cg, layout = 'dendrogram')
# unrooted <- create_layout(cg, layout = 'unrooted')
# matrix <- create_layout(cg, layout = 'matrix')
# hive <- create_layout(cg, layout = 'hive')
fabric <- create_layout(df_graph, layout = 'fabric')

# graphlayouts
# nicely <- create_layout(df_graph, layout = "nicely")
# stress <- create_layout(cg, layout = "stress")
# radial <- create_layout(cg, layout = "focus", focus = 1)

```

# Section
## Subsection


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source='fold-hide', fig.align='center', out.width="100%"}

theme_opts <- theme(
    text = element_text(family = "inconsolata"), 
    # plot.margin = unit(c(1.5,1,1,1), "in"),
    legend.position='none'
)

v1 <- ggraph(sugiyama) + 
  #geom_edge_link(aes(colour = factor(km), edge_width = edge_weights)) + 
  geom_edge_link() +
  geom_node_point() +
  #geom_node_text(aes(label = name)) +
  theme_graph()+
  theme_opts

girafe(ggobj = v1, width_svg = 16, height_svg = 9,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))


```


### References
#### citations for narrative and data sources


```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-hide'}

# eval = FALSE as default; run manually as chunk
# PUSH TO PRODUCTION
source("../../../z-scripts/create_production_output.R", local = knitr::knit_global())

```




```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


