---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    # css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      # in_header: "../../../z-assemblers/fragments/header.html"
      # after_body: "../../../z-assemblers/fragments/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(dplyr)
library(tidyr)
library(forcats)
library(ggplot2)
library(ggridges)
library(wesanderson)

library(knitcitations)
library(bibtex)

```

<div class="activity">
TEMPORALS
</div>

# Ridgeline Plot
## Food Consumption by CO2 Emissions

***

## Load data [Ingest]

```{r, echo=FALSE}

# Load data

food_consumption = read.csv("archetypes/food_consumption-by-co2-emissions.csv", header = TRUE, stringsAsFactors = TRUE)
food_consumption

```


## Prepare data [Wrangle]


```{r}

food_consumption <- food_consumption %>% filter(co2_emmission>=10)

food_consumption <- food_consumption %>% mutate(food_category = fct_reorder(food_category,co2_emmission))

food_consumption

```


## Plot [ Views / Temporals ]


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=6, , fig.align='center', out.width="100%"}

pal <- wes_palette("Zissou1", 10, type = "continuous")

v1 = ggplot(food_consumption, aes(x=co2_emmission, y=food_category, fill=food_category)) +
    geom_density_ridges() +
    scale_x_continuous(trans="log10") +
    scale_fill_manual(values = pal) +
    scale_color_manual(values = pal) +
    theme_bw() +
    theme(
        panel.border     = element_blank(),
        legend.position="none"
      ) +
    xlab("CO2 Emissions") +
    ylab("")
v1

```

## Plot [ Views / Temporals ]

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=6, , fig.align='center', out.width="100%"}

v2 = ggplot(food_consumption, aes(x=co2_emmission, y=food_category, fill=food_category)) +
    stat_density_ridges( quantile_lines = TRUE,
          jittered_points = TRUE,
          position = position_points_jitter(width = 0.05, height = 0),
          point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.7) +
    scale_x_continuous(trans="log10") +
    scale_fill_manual(values = pal) +
    scale_color_manual(values = pal) +
    theme_bw() +
    theme(
        panel.border     = element_blank(),
        legend.position="none"
      ) +
    xlab("CO2 Emissions") +
    ylab("")
v2

```



```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Save plot to svg file
# ggsave(filename = "food_consumption-by-co2-emissions-v1.svg", plot = v1, width=24.5, height=13)
# ggsave(filename = "food_consumption-by-co2-emissions-v2.svg", plot = v2, width=24.5, height=13)

```





# References
## The citations and data sources used for this case can be found at 
<a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-02-18/readme.md" target="_blank"> Data Source</a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

 cleanbib()
 read.bibtex(file = "citations/food_consumption-by-co2-emissions.bib")

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


