---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999) # turn-off scientific notation like 1e+48

library(htmltools) # needed to include html snippets
library(tidyverse)

# needed to include bib references
library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS
</div>

# Bar Polar
## Real-life case: Antibiotic Effectiveness Charting

> Don't call the world dirty because you forgot to clean your glasses...\
--- Aaron Hill\



***

# Load the data
## Load the antibiotic effectiveness data table

```{r load-data, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Create dataset
data <- data.frame(
  id=as.factor(seq(1,60)),
  individual=paste( "Mister ", seq(1,60), sep=""),
  value=sample( seq(10,100), 60, replace=T)
)

```


# Plot the chart

```{r draw-plot, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-show', fig.width=10.5, fig.height=10.5}

p <- ggplot(data, aes(x=id, y=value)) +       # Note that id is a factor. If x is numeric, there is some space between the first bar
  
  # This add the bars with a blue color
  geom_bar(stat="identity", fill=alpha("blue", 0.3)) +
  
  # Limits of the plot = very important. The negative value controls the size of the inner circle, the positive one is useful to add size over each bar
  #ylim(-100,100) +
  
  # Custom the theme: no axis title and no cartesian grid
  # theme_minimal() +
  # theme(
  #   axis.text = element_blank(),
  #   axis.title = element_blank(),
  #   panel.grid = element_blank(),
  #   plot.margin = unit(rep(-2,4), "cm")     # This remove unnecessary margin around plot
  # ) +
  
  # This makes the coordinate polar instead of cartesian.
  coord_polar(start = 0)

p

```


# References
## The citations and data sources used for this case

Source: <a href="https://peltiertech.com/antibiotic-effectiveness-charting-revisited/">Antibiotic Effectiveness Charting</a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

cleanbib()
options("citation_format" = "pandoc")
read.bibtex(file = "./citations/burtin-bacteria.bib")

```

