---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(sf)
library(geojsonio)
library(ggplot2)

```

<div class="activity">
MAPS  
</div>

***

# Section
## Subsection

```{r, message=FALSE, warning=FALSE, echo=FALSE, results=FALSE}

# MAP SOURCES

# BASE MAP

land <- topojson_read("archetypes/un-default/BNDA50-LAND-no-ATA-09.topojson")
borders <- topojson_read("archetypes/un-default/BNDL50-BORDERS-no-ATA-09.topojson")
type_3 <- topojson_read("archetypes/un-default/BNDL50-BORDERS-TYPE-3.topojson")
type_4 <- topojson_read("archetypes/un-default/BNDL50-BORDERS-TYPE-4.topojson")


```


## Set crs


```{r}

land <- land %>% st_as_sf() %>% st_set_crs(4326)
type_3 <- type_3 %>% st_as_sf() %>% st_set_crs(4326)
type_4 <- type_4 %>% st_as_sf() %>% st_set_crs(4326)
# point <- st_as_sf(point, coords = c("long", "lat"), crs = 4326)

```


## Shared Theme


```{r}

# theme parameters
theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

```

## Mercator

## Cylindrical Projection – Robinson

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=8, out.width = "85%"}


# In order of layer placement top -> down
v1 = ggplot() +
  geom_sf(data = land, color="#AAAAAA", fill="#FFFFFF", size=0.5) +
  # geom_sf(data = borders, color="#CCCCCC") +
  geom_sf(data = type_3,linetype = "dotted", color="red", size=0.5) +
  geom_sf(data = type_4,linetype = "dashed", color="blue", size=0.5) +
  scale_x_continuous() +
  scale_y_continuous() +
  coord_sf(crs = "+proj=robin") +
  theme_bw() +
  labs(x="", # Longitude
       y="", # Latitude
       title = "Topojson Vector Map", 
       subtitle="Land and Borders") +
  theme_opts

v1

```


## Cylindrical Projection – Gall-Peters

## Cylindrical Projection – Transverse Mercator

## Winkel Tripel


```{r}

```


```{r, echo=FALSE}

# ggsave(filename = "vector-topojson-map.svg", plot = v1, width=11, height=6)

```


# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case


```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```
