---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48


library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS  
</div>

# Ternary Plot
## Depicts Ratios of Three Variables


Ternary Plot or also know as the __Triangle__ __Graph__ is a perfect way to showcase the ratios of three variables. Ternary Graphs visualize the ratios between the three variables, by simply positioning a dot in accordance with its position on each of the three axes using barycentric coordinates.



Typical Uses:

* __Visualizing Data points__ : Visualize how data is distributed in a data set.
* __Classification__ : Done by breaking up areas of the ternary plot into different categories
* __Flammability Diagram__ : Show flammability in mixtures of fuel, oxygen and inert gas
* __Genetics__ : population genetics can be showcase in a variation of Ternary plot called de Finetti diagram.


A fourth variable can also be added into a ternary plot. For example, we can visualize the fourth variable by filling the plot with varying shades of color. We can chart a bubble graph inside a ternary plot (variations the size of the circle of the data points).



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

