---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/kamino.css", "../../../z-assemblers/temporals.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/header.html"
      after_body: "../../../z-assemblers/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation


library(tidyverse)
library(ggridges)
library(lubridate)
library(forcats)

library(htmltools) # needed to include html snippets
library(knitcitations)
library(bibtex)

```

<div class="activity">
TEMPORALS
</div>

# Skyline Chart


***

# Section
## Subsection

```{r}

df = read.csv("../archetypes/MORTGAGE30US.csv", header = TRUE, stringsAsFactors = FALSE)  # read text file 
df <- df %>% mutate(yearf=factor(year))
df <- filter(df,year>2009)
df

```

# Section
## Subsection

```{r, echo=FALSE, fig.width=10.5, fig.height=7.5}

ggplot(data=df,
       aes(y=fct_reorder(yearf,-year),
           x=pmms30,group=fct_reorder(yearf,-year),
           fill=yearf))+
  geom_density_ridges2(color="black",size=0.2,
                       alpha=0.85,scale=0.75, 
                       stat="binline",
                       binwidth=0.125)+
  geom_text(stat = "bin",
            aes(y = group + 0.9*(..count../max(..count..)),
                label = ifelse(..count..>0, ..count.., "")
                ),
            vjust = 0.2, size = 4, color = "black", binwidth = 0.125) +
  geom_vline(data= .%>% filter(date==max(date)), linetype=2, color="black",aes(xintercept=pmms30))+
  scale_fill_viridis_d(option="C")+
  scale_color_viridis_d(option="C")+
  scale_x_continuous(limits=c(2,6),breaks=seq(2,6,0.25))+
  theme(panel.grid.minor=element_blank(),
        legend.position="none",
        plot.title=element_text(size=rel(1.5),face="bold"),
        plot.subtitle=element_text(size=rel(1.3),face="italic"),
        panel.grid.major.x=element_blank())+
  labs(x="30-year fixed mortgage rate (%)\n",
       y="Year",
       caption=paste0("@lenkiefer Source: Freddie Mac Primary Mortgage Market Survey,",
                      "\nDotted line at ",
                      df[df$date==max(df$date),]$pmms30,"% average for week of ",
                      as.character(max(df$date), format="%B %d, %Y")),
       title="Distribution over weekly mortgage rates by year",
       subtitle="Histograms fit to weekly observations for each year\n")

```

# Section
## Subsection

```{r, echo=FALSE}

# ggsave(filename = "skyline.svg", plot = v1, width=11, height=6)

```



# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case



```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```


```{r, message=FALSE, warning=FALSE, echo=FALSE}

# echo=FALSE will exclude block from code folding
# Example for including external html content when needed
htmltools::includeHTML("mark-complete-button.html")

```



```{r, child='mark-complete-click.Rmd'}

# JS event handler for button click

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

