---
title: "Dot Density"
output: 
  html_document:
    theme: flatly
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)

options(scipen=999)  # turn-off scientific notation like 1e+48

library(maptools)
library(sp)
library(sf)
library(rgdal)
library(raster)
library(rgeos)

library(tidyverse)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggthemes)

```

## Dot Density Map - Raster to Vector Transform


```{r, message=FALSE, warning=FALSE, echo = FALSE}

# Load density file
the_raster <- raster("../archetypes/geo-wiki-livestock/DUCKS/GLb_Ducks_CC2006_AD.tif")
the_raster

levels(the_raster)
cellStats(the_raster, sd)
hist(the_raster)



```


```{r}

# For very large files, aggregate to reduce precision
the_raster_agg <- aggregate(the_raster, fact = 10, fun = mean)
class(the_raster_agg)

# remove loaded file
rm(the_raster)

```



```{r}

the_raster_df <- as.data.frame(the_raster_agg, xy = TRUE) 
rm(the_raster_agg)
str(the_raster_df)

```



```{r, echo=FALSE, fig.width=12, fig.height=6}

the_raster_df <- filter( the_raster_df, GLb_Ducks_CC2006_AD != "NA")
the_raster_df <- filter( the_raster_df, GLb_Ducks_CC2006_AD > 1)

write.csv(the_raster_df,"../archetypes/livestock-ducks.csv", row.names = FALSE)
# rm(pigs_livestock_df)
# pigs_livestock_df <- read.csv("../archetypes/livestock-pigs.csv", header = TRUE)

head(the_raster_df)
str(the_raster_df)

# unique(pigs_livestock_df$Glb_Pigs_CC2006_AD)
min(the_raster_df$GLb_Ducks_CC2006_AD)
max(the_raster_df$GLb_Ducks_CC2006_AD)
summary(the_raster_df$GLb_Ducks_CC2006_AD)
# hist(pigs_livestock_df$Glb_Pigs_CC2006_AD)

```



```{r, echo=FALSE, fig.width=12, fig.height=6}

theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

# PLOT NATURAL EARTH BORDERS
ne_world <- ne_countries(scale = "small", returnclass = "sf")
# class(ne_world)

# removes Antarctica
ne_world <- filter(ne_world, iso_a3 != "ATA") 

v1 <- ggplot(data = ne_world) +
  geom_sf(fill="#d5d8d0", color="#a7aeb2", stroke=0.25) +
  geom_raster(data = the_raster_df,
              aes(x = x, y = y, alpha = GLb_Ducks_CC2006_AD) ) + 
  #scale_fill_manual(values =  c("#b3d9de", "#89c5cb", "#4eaaac", "#06a6ab", "#009aa0", "#03646b", "#073b3a"), guide = "none") +
  scale_alpha_continuous(range =  c(0.9, 0.1), guide = "none") +
  coord_sf() +
  theme_opts

v1


```


