---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE, echo=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

# Libraries
library(tidyverse)
library(data.table)
library(plyr)
library(jpeg)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(geosphere)
library(grid)
library(ggiraph)

```

<div class="activity">
MAPS  
</div>

# Connection Map
## Mapping airline routes of British Airlines



***

# Load data
## Routes and lights

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

flights_routes <- read.csv("archetypes/flight-routes/british-airways.csv", header = TRUE)

flights_points <- flights_routes %>%
  group_by(group) %>%
  filter(row_number() == 1 | row_number() == n())

flights_points

# use city populations to simulate lights as in original
lights = read.csv("archetypes/cities-top-10000-world.csv", header = TRUE, stringsAsFactors = FALSE)
lights

```


## Natural Earth base maps


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# PLOT NATURAL EARTH BORDERS
ne_world <- ne_countries(scale = "small", returnclass = "sf")
# removes Antarctica
ne_world <- filter(ne_world, iso_a3 != "ATA")

```


# Plot
## Theme, light and dark


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

theme_opts <- theme(
      axis.line=element_blank(),
      axis.text.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      legend.position="none",
      legend.title = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background=element_rect(fill="#0d0e1b", colour="#0d0e1b"),
      panel.border = element_blank()
)

theme_dark <- theme(
      panel.background=element_rect(fill="#0d0e1b", colour="#0d0e1b")
)

theme_light <- theme(
      panel.background=element_rect(fill="#ffffff", colour="#ffffff")
)


```


## Dark


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=6, out.width = "100%"}

v1 <- ggplot() +
  # Draw the natural earth map  styling to match blue marble dark lights
  geom_sf(data = ne_world, fill="#0f1227", color="#1c3153", stroke=1.0) +
  # Plot all the lights of the cities at night
  geom_point(data = lights, aes(x=lng, y=lat, alpha=Population), size=0.5, color="#ffffff" ) +
  # routes
  geom_path(data = flights_routes, aes(long, lat, group = id, color = name), alpha = 0.2, size = 0.5) + 
  # airline hubs
  geom_point(data = flights_points, aes(long, lat), alpha = 0.3, size = 1, colour = "#f9ba00") +
  # brightness by population
  scale_alpha_continuous(range=c(0.1,1), guide=FALSE) +
  # color by airline
  scale_color_manual(values = c("#f9ba00", "#075aaa", "#ff0000")) +
  theme_bw() +
  labs(x="",
       y="",
       title = "Airline Flight Routes", 
       subtitle="") +
  theme_opts +
  theme_dark

girafe(ggobj = v1, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```


## Light


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=6, out.width = "100%"}

v2 <- ggplot() +
  
  geom_sf(data = ne_world, fill="#f5f5f5", color="#d5d5d5", stroke=1.0) +
  # lights
  geom_point(data = lights, aes(x=lng, y=lat, alpha=Population), size=0.5, color="#777777" ) +
  # routes
  geom_path(data = flights_routes, aes(long, lat, group = id, color = name), alpha = 0.2, size = 0.5) + 
  # airline hubs
  geom_point(data = flights_points, aes(long, lat), alpha = 0.3, size = 1, colour = "#075aaa") +
  # brightness by population
  scale_alpha_continuous(range=c(0.1,1), guide=FALSE) +
  # color by airline
  scale_color_manual(values = c("#075aaa", "#f9ba00", "#ff0000")) +
  theme_bw() +
  labs(x="",
       y="",
       title = "Airline Flight Routes", 
       subtitle="") +
  theme_opts +
  theme_light

girafe(ggobj = v2, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```


## Save output to file


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# ggsave(filename = "assets/airline-flight-routes-dark.svg", plot = v1, width=12, height=6)
# ggsave(filename = "assets/airline-flight-routes-light.svg", plot = v2, width=12, height=6)

```


# Exercises and practice
## Knime and R practice solutions

<a href="https://openflights.org/data.html">Source</a>

# References
## The citations and data sources used for this case



```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```




```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```



