---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    #self_contained: false
    #lib_dir: libs
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(reshape)
library(ggplot2)
library(ggridges)
library(ggthemes)
library(wesanderson)

```

<div class="activity">
MAPS  
</div>

# Ridgeline Map
## R Markdown


***

# Section
## Subsection

```{r, echo=FALSE}

# this is process intensive; run garbage collection to free memory
gc()

xyz_df <- read.csv("./archetypes/world-population-lines-long.csv", header = TRUE)
xyz_df

xyz_df_zero <- read.csv("./archetypes/world-population-lines-long-zeros.csv", header = TRUE)
xyz_df_zero

summary(xyz_df)
xyz_df
#unique(xyz_df$y)

```

# Section
## Subsection

```{r, echo=FALSE, fig.width=12, fig.height=6}

theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  #panel.grid = element_blank(),
  panel.grid.major = element_line(colour="#ffffff"),
  panel.grid.minor = element_line(colour="#ffffff"),
  panel.background=element_rect(fill="#f0f0f0", colour="#f0f0f0"),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

v1 <- ggplot(xyz_df, aes(x, y, height = population, group = y)) + 
  geom_density_ridges(stat = "identity", scale = 40, size=0.1, color = "#666666", fill = "#ffffff") + 
  scale_y_reverse(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  theme_bw() +
  theme_opts

v1



```

# Section
## Subsection

```{r}

range01 <- function(x){(x-min(x))/(max(x)-min(x))}
color_condition <- function(x) { ifelse(x==0, "transparent", "#666666")  }

#Add 180 to the latitude to remove negatives in southern hemisphere, then order them.
xyz_df_zero$npop <- range01(xyz_df_zero$population) * 0.2
xyz_df_zero$ny<-range01(xyz_df_zero$rank)
xyz_df_zero$nx<-range01(xyz_df_zero$x)
xyz_df_zero$ord <- xyz_df_zero$ny
xyz_df_zero_s <- xyz_df_zero[order(-xyz_df_zero$ord),]

v2 <- ggplot()
for (i in unique(xyz_df_zero_s$ord))
{
#print(i)
v2 <- v2 +
  geom_polygon(data = xyz_df_zero_s[xyz_df_zero_s$ord==i,], aes(nx, npop+ny, group = ny ), size=0.2, fill="white", color="white") + 
  # geom_polygon(data = xyz_df_zero_s[xyz_df_zero_s$ord==i,], aes(nx, npop+ny, group = ny, fill = population ), size=0.2, color="white") + 
  geom_path(data = xyz_df_zero_s[xyz_df_zero_s$ord==i,], 
            aes(nx, npop+ny, group = ny ), 
            color = color_condition(xyz_df_zero_s[xyz_df_zero_s$ord==i,]$npop), size = 0.2, lineend = "round")
}

#show plot!
v2 +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_bw() +
  theme_opts

```



# Section
## Subsection

```{r}

#ggsave(filename = "world-population-ridgeline-xyz-v1.svg", plot = v1, width=12, height=6)
#ggsave(filename = "world-population-ridgeline-xyz-v2.svg", plot = v2, width=12, height=6)

```



# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case

<a href="https://govdata360-backend.worldbank.org/api/v1/datasets/4034/dump.csv">Source</a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```








```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


