---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999) # turn-off scientific notation like 1e+48

library(htmltools) # needed to include html snippets
library(readr)
library(vcd)

# needed to include bib references
library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS
</div>

# Mosaic
## Real-life case: Titanic

***

# Load the data
## Titanic survivors

```{r load-data, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# input data
titanic <- read_csv("../archetypes/titanic.csv")
head(titanic)

# create a table
tbl <- xtabs(~Survived + Class + Sex, titanic)
ftable(tbl)

```

# Plot the chart
## Titanic survivors by class, sex and age

```{r draw-plot, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-show', fig.width=13, fig.height=8}

mosaic(tbl, 
       shade = TRUE,
       legend = TRUE,
       labeling_args = list(set_varnames = c(Sex = "Gender",
                                             Survived = "Survived",
                                             Class = "Passenger Class")),
       set_labels = list(Survived = c("No", "Yes"),
                         Class = c("1st", "2nd", "3rd", "Crew"),
                         Sex = c("F", "M")),
       main = "Titanic Data")

```

# Exercises and practice
## Knime and R practice solutions


# References
## The citations and data sources used for this case

Source: <a href="">Titanic Survivors</a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

cleanbib()
options("citation_format" = "pandoc")
#read.bibtex(file = "../archetypes/...bib")

```


```{r mark-complete-button, message=FALSE, warning=FALSE, echo=FALSE}

# echo=FALSE will exclude block from code folding
# Include external html content for “Mark Complete” button
htmltools::includeHTML("mark-complete-button.html")

```


```{r mark-complete-click, child='mark-complete-click.Rmd'}

# JS event handler for button click

```


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

