---
pagetitle: "Global Steel Plant Tracker"
output:
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: ["../../../z-assemblers/fragments/google-analytics.html", "../../../z-assemblers/fragments/header.html"]
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel)
library(ggiraph)

library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Inconsolata", "inconsolata")
# turn on showtext
showtext_auto()

```

<div class="activity">
MAPS  
</div>

***

# Global Steel Plant Tracker
## Subsection

```{r, echo=FALSE}

coal_mines <- read.csv("archetypes/global-energy-monitor/global-steel-plant-tracker-data.csv", header = TRUE, stringsAsFactors = FALSE)
coal_mines

```


### Base map
#### natural earth


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-show'}

ne_world <- ne_countries(scale = "small", returnclass = "sf")
ne_world <- filter(ne_world, iso_a3 != "ATA")

```


### View
#### natural earth


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source='fold-hide', fig.align='center', out.width="100%"}

theme_opts <- theme(
  legend.position = "bottom",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

# color palette to use
pal <- wes_palette("Zissou1", 10, type = "continuous")

v1 <- ggplot(data = ne_world) +
  geom_sf(fill="white", color="#888888", stroke=0.5) +
  geom_point( data = df, aes(x=lng, y=lat), size=2.0, color="black", alpha=0.8) +
  scale_size_continuous(range=c(1,12)) +
  scale_fill_gradientn(colours = pal) + 
  scale_color_gradientn(colours = pal) + 
  theme_bw() +
  labs(x="Longitude",
       y="Latitude",
       title = "Bubble Map", 
       subtitle="Top 10000 Cities of the World") +
  theme_opts

v1

```


### References
#### Citations and data sources


```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-hide'}

# eval = FALSE as default; run manually as chunk
# PUSH TO PRODUCTION
source("../../../z-scripts/create_production_output.R", local = knitr::knit_global())

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

