---
pagetitle: "Energy Consumption by Country & Fuel Type"
output:
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: ["../../../z-assemblers/fragments/google-analytics.html", "../../../z-assemblers/fragments/header.html"]
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE, dev='svg')
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memory and report the memory usage.

library(tidyverse)
library(ggalluvial)
library(ggrepel)
library(ggiraph)

library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Inconsolata", "inconsolata")
# turn on showtext
showtext_auto()

```

<div class="activity">
TEMPORALS
</div>

# Energy Consumption by Country & Fuel Type
## alluvial

***


```{r, echo=TRUE}

df <- read.csv("./archetypes/owid-energy-data-long.csv", header = TRUE, stringsAsFactors = FALSE)  # read text file 
df

```


### Section
#### Subsection


```{r}

# Filter for the fields used in each view
consumption_types <- c("wind_electricity", 
                  "renewables_electricity", 
                  "solar_electricity", 
                  "hydro_electricity", 
                  "renewable_electricity", 
                  "fossil_electricity", 
                  "wind_consumption", 
                  "oil_electricity")

df <- df %>% filter(variable %in% consumption_types)

# Limit to evry 2 years intervals
years <- c(2000, 2002, 2004,2006,2008,2010,2012,2014, 2016)
df <- df %>% filter(year %in% years)

# The specific country to generate the view
df_country <- df %>% filter(country == "Ethiopia")

df_country

# Color palette for each energy type
energy_pal <- c("wind_electricity" = "#72A06A", 
                "renewables_electricity" = "#36454f", 
                "solar_electricity" = "#373A36", 
                "hydro_electricity" = "#7b9095", 
                "renewable_electricity" = "#386890", 
                "fossil_electricity" = "#FDB813", 
                "oil_electricity" = "#7da7ca")

# Standard theme options to use for each view
theme_opts <- theme(
  legend.position = "bottom",
  legend.title = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank()
)

```



### Section
#### Subsection


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source='fold-hide', fig.align='center', out.width="100%"}

# View using alluvium geom
v1 <- ggplot(data = df_country, aes(x = year, y = value, alluvium = variable)) +
  geom_alluvium(aes(fill = variable), size=1.5, colour = "#ffffff", alpha = 1.0, decreasing = FALSE) +
  # for set years
  scale_x_continuous(breaks = years) +
  # for aesthetics to show top-down
  scale_y_reverse() +
  # use the palette defined above
  scale_fill_manual(values = energy_pal) +
  # in case any marks fall outside panel
  coord_cartesian(clip = "off") +
  # a simple theme to modify
  theme_minimal() +
  # rotate years
  theme(axis.text.x = element_text(angle = -90, hjust = 1, vjust = 0.5)) +
  # use configured theme options
  theme_opts +
  labs(
    x="",
    y="",
    title="Country Energy Consumption by Fuel Type",
    subtitle="Ethiopia"
  )

girafe(ggobj = v1, width_svg = 16, height_svg = 14,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```


### Section
#### Subsection


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source='fold-hide', fig.align='center', out.width="100%"}

v2 <- ggplot(data = df_country, aes(x = year, y = value, alluvium = variable)) +
  geom_flow(aes(fill = variable, size = value), colour = "#ffffff", alpha = 1.0, decreasing = FALSE) +
  # for set years
  scale_x_continuous(breaks = years) +
  # for aesthetics to show top-down
  scale_y_reverse() +
  # use the palette defined above
  scale_fill_manual(values = energy_pal) +
  # scale line size so smallest values still show
  scale_size_continuous(range = c(0.75,2), breaks = c(0.75,2), guide = FALSE) +
  # in case any marks fall outside panel
  coord_cartesian(clip = "off") +
  # a simple theme to modify
  theme_minimal() +
  # rotate years
  theme(axis.text.x = element_text(angle = -90, hjust = 1, vjust = 0.5)) +
  # use configured theme options
  theme_opts +
  labs(
    x="",
    y="",
    title="Country Energy Consumption by Fuel Type",
    subtitle="Ethiopia"
  )

girafe(ggobj = v2, width_svg = 16, height_svg = 14,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```


### References
#### citations for narrative and data sources

Source: The Data can be retrieved from <a href="https://ourworldindata.org/energy-production-consumption" target="_blank"> Energy Production and Consumption </a>


```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-hide'}

# eval = FALSE as default; run manually as chunk
# PUSH TO PRODUCTION
source("../../../z-scripts/create_production_output.R", local = knitr::knit_global())

```


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


