---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    # css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      # in_header: "../../../z-assemblers/fragments/header.html"
      # after_body: "../../../z-assemblers/fragments/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

library(reshape2)
library(tidyverse)
library(stringr)
library(ggplot2)
library(ggalluvial)
library(gridExtra)
library(ggthemes)

library(knitcitations)
library(bibtex)

```

<div class="activity">
TEMPORALS
</div>

# Alluvial Plot
## Energy Consumption by Country & Fuel Type

***


```{r, echo=TRUE}

df = read.csv("./archetypes/owid-energy-data-long.csv", header = TRUE, stringsAsFactors = FALSE)  # read text file 

# Filter for the fields used in each view
consumption_types <- c("wind_electricity", 
                  "renewables_electricity", 
                  "solar_electricity", 
                  "hydro_electricity", 
                  "renewable_electricity", 
                  "fossil_electricity", 
                  "wind_consumption", 
                  "oil_electricity")

df <- df %>% filter(variable %in% consumption_types)

# Limit to evry 2 years intervals
years <- c(2000, 2002, 2004,2006,2008,2010,2012,2014, 2016)
df <- df %>% filter(year %in% years)

# The specific country to generate the view
df_country <- df %>% filter(country == "Ethiopia")

df_country

# Color palette for each energy type
energy_pal <- c("wind_electricity" = "#72A06A", 
                "renewables_electricity" = "#36454f", 
                "solar_electricity" = "#373A36", 
                "hydro_electricity" = "#7b9095", 
                "renewable_electricity" = "#386890", 
                "fossil_electricity" = "#FDB813", 
                "oil_electricity" = "#7da7ca")

# Standard theme options to use for each view
theme_opts <- theme(
  legend.position = "bottom",
  legend.title = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank()
)

```

# Section
## Subsection

```{r, echo=TRUE, fig.width=11, fig.height=6}

# View using alluvium geom
v1 <- ggplot(data = df_country, aes(x = year, y = value, alluvium = variable)) +
  geom_alluvium(aes(fill = variable), size=1.5, colour = "#ffffff", alpha = 1.0, decreasing = FALSE) +
  # for set years
  scale_x_continuous(breaks = years) +
  # for aesthetics to show top-down
  scale_y_reverse() +
  # use the palette defined above
  scale_fill_manual(values = energy_pal) +
  # in case any marks fall outside panel
  coord_cartesian(clip = "off") +
  # a simple theme to modify
  theme_minimal() +
  # rotate years
  theme(axis.text.x = element_text(angle = -90, hjust = 1, vjust = 0.5)) +
  # use configured theme options
  theme_opts +
  labs(
    x="",
    y="",
    title="Country Energy Consumption by Fuel Type",
    subtitle="Ethiopia"
  )

v1

```

# Section
## Subsection

```{r, echo=TRUE, fig.width=11, fig.height=7.5}

v2 <- ggplot(data = df_country, aes(x = year, y = value, alluvium = variable)) +
  geom_flow(aes(fill = variable, size = value), colour = "#ffffff", alpha = 1.0, decreasing = FALSE) +
  # for set years
  scale_x_continuous(breaks = years) +
  # for aesthetics to show top-down
  scale_y_reverse() +
  # use the palette defined above
  scale_fill_manual(values = energy_pal) +
  # scale line size so smallest values still show
  scale_size_continuous(range = c(0.75,2), breaks = c(0.75,2), guide = FALSE) +
  # in case any marks fall outside panel
  coord_cartesian(clip = "off") +
  # a simple theme to modify
  theme_minimal() +
  # rotate years
  theme(axis.text.x = element_text(angle = -90, hjust = 1, vjust = 0.5)) +
  # use configured theme options
  theme_opts +
  labs(
    x="",
    y="",
    title="Country Energy Consumption by Fuel Type",
    subtitle="Ethiopia"
  )

v2

```

```{r, echo=FALSE}

# Save plot to svg file
# ggsave(filename = "alluvial-country-energy-consumption-Ethiopia-v1.svg", plot = v1, width=12, height=6)
# ggsave(filename = "alluvial-country-energy-consumption-Ethiopia-v2.svg", plot = v2, width=12, height=6)

```



# References
## The citations and data sources used for this case

Source: The Data can be retrieved from <a href="https://ourworldindata.org/energy-production-consumption" target="_blank"> Energy Production and Consumption </a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

 cleanbib()
 read.bibtex(file = "citations/country-energy-consumption.bib")

```




```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


