---
pagetitle: "Soybean Production"
output:
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: ["../../../z-assemblers/fragments/google-analytics.html", "../../../z-assemblers/fragments/header.html"]
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE, dev='svg')
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memory and report the memory usage.

library(tidyverse)
library(janitor)
library(ggsankey)
library(scales)
library(ggtext)
library(ggiraph)

library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Inconsolata", "inconsolata")
# turn on showtext
showtext_auto()

```

<div class="activity">
TEMPORALS
</div>

# Soybean Production
## alluvial


```{r, echo=FALSE}

soybean_use = read.csv("archetypes/soybean-production/soybean-production.csv", header = TRUE, stringsAsFactors = FALSE)  # read text file 
soybean_use

```


### Section
#### Subsection


```{r, echo=FALSE, fig.width=11, fig.height=6}

top <- soybean_use %>% 
    filter(!is.na(code),
           code != "OWID_WRL",
           year == 2013) %>% 
    group_by(entity) %>% 
    mutate(total_use = sum(human_food, animal_feed, processed, na.rm = TRUE)) %>% 
    arrange(desc(total_use)) %>% 
    ungroup() %>% 
    select(entity, total_use) %>% 
    distinct() %>% 
    arrange(total_use) %>% 
    mutate(row = row_number(),
           label_pos = cumsum(total_use)-(total_use/2))


d_soy <- soybean_use %>% 
  filter(!is.na(code),
         code != "OWID_WRL") %>% 
  group_by(entity, year) %>% 
  mutate(total_use = sum(human_food, animal_feed, processed, na.rm = TRUE),
         fill_entity = case_when(entity == "China" ~ "#B43718", 
                                 entity == "India" ~ "#D7431D", 
                                 entity == "Japan" ~ "#E45C3A", 
                                 entity == "Taiwan" ~ "#E9795D", 
                                 entity == "Indonesia" ~ "#EE9781", 
                                 entity == "Thailand" ~ "#EE9781",
                                 
                                 entity == "Russia" ~ "#33014A",
                                 
                                 entity == "United States" ~ "#023579",
                                 entity == "Canada" ~ "#0247A1",
                                 
                                 entity == "Brazil" ~ "#11403B", 
                                 entity == "Argentina" ~ "#1A615A", 
                                 entity == "Mexico" ~ "#228177", 
                                 entity == "Paraguay" ~ "#2BA195", 
                                 entity == "Bolivia" ~ "#33C1B3", 
                                 
                                 entity == "Germany" ~ "#4997FD", 
                                 entity == "Spain" ~ "#72AEFE", 
                                 entity == "Netherlands" ~ "#9AC5FE", 
                                 entity == "Italy" ~ "#C2DCFE", 
                                 
                                 entity == "Egypt" ~ "#F7C8A1", 
                                 entity == "Turkey" ~ "#FADEC7", 
                                 
                                 !(entity %in% c("China", "India", "Japan", "Taiwan", "Indonesia", "Thailand", 
                                                 "Russia", "United States", "Canada", 
                                                 "Brazil", "Argentina", "Mexico", "Paraguay", "Bolivia",
                                                 "Germany", "Spain", "Netherlands", "Italy",
                                                 "Egypt", "Turkey")) ~ "#e5e5e5")) %>% 
  ungroup() %>% 
  left_join(top, by = "entity")

d_soy %>% 
  filter(year %in% c(1961, 2013)) %>% 
  group_by(year == 2013) %>% 
  summarise(total_use = sum(total_use.x))

rm(top, soybean_use)

```


### Section
#### Subsection


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source='fold-hide', fig.align='center', out.width="100%"}

v1 <- d_soy %>% 
  ggplot(aes(year, node = entity, fill = fill_entity, colour = fill_entity, value = total_use.x)) + 
  geom_sankey_bump(space = 0, type = "alluvial", color = "transparent", smooth = 6, alpha = 0.8) + 
  # annotation_custom(grob = grid::rectGrob(gp = grid::gpar(col = NA, fill = "white")), xmin = 2013.4) + 
  geom_text(data = subset(d_soy, year == 2013 & fill_entity != "#e5e5e5"), aes(y = label_pos, label = entity), nudge_x = 0.5, hjust = 0, size = 8) + 
  scale_fill_identity() + 
  scale_colour_identity() + 
  scale_y_continuous(breaks = seq(0, 250000000, 50000000), labels = seq(0, 250, 50), expand = c(0, 0)) + 
  scale_x_continuous(breaks = seq(1960, 2010, 5), labels = seq(1960, 2010, 5), limits = c(1961, 2018), expand = c(0, 0)) + 
  labs(title = "Global Soybean Use",
       subtitle = "Between 1961 and 2013, global soybean use increased from 22 million tonnes to 255 million tonnes.",
       y = "use after trade (million tonnes)",
       x = NULL,
       caption = "production minus exports plus imports.") + 
  theme(legend.position = "none",
        panel.background = element_rect(fill = NA),
        panel.grid.major.y = element_line(colour = "grey95"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        text = element_text(colour = "black", family = "inconsolata", size = 14),
        axis.text = element_text(colour = "black", family = "inconsolata"),
        axis.line.x = element_blank(),
        plot.caption = element_text(size = 14, lineheight = 0.3))

girafe(ggobj = v1, width_svg = 16, height_svg = 14,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))


```


### References
#### citations for narrative and data sources

Source: Our World in Data | Visualisation: @Andy_A_Baker



```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-hide'}

# eval = FALSE as default; run manually as chunk
# PUSH TO PRODUCTION
source("../../../z-scripts/create_production_output.R", local = knitr::knit_global())

```


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

