---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs

---


```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE,
   dev = "svg")
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memory and report the memory usage.

library(knitcitations)
library(bibtex)
library(changepoint)
library(AnomalyDetection)
library(tidyverse)
library(rvest)
library(ggiraph)

```

<div class="activity">
ANALYTICS 
</div>

# Change
# Case: Climate Change in Ethiopia


***

# Load the annual mean temperature data
```{r load-data, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}


df<-read_csv('archetypes/tas_timeseries_annual_cru_1901-2020_ETH.csv')
df
```



# Multiple Changes in Mean and Variance

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}


df1.pelt=cpt.meanvar(df$Ethiopia,
      method='BinSeg',Q=20,penalty="SIC")
points <- cpts(df1.pelt)

for(i in points){
  print(paste0('Change Point Year :' ,df$Year[i]))
}





param.est(df1.pelt)
plot(df1.pelt,cpt.width=1,cpt.col='red')

for(i in points){
  abline(v=i, col="blue")
}


```



# References
### The data source is from [World Bank Climate Knowledge Portal](https://climateknowledgeportal.worldbank.org/download-data)
### [Famine in Ethiopia: Update April 18, 2000](https://reliefweb.int/report/eritrea/famine-ethiopia-update-april-18-2000)
### [Climate Change Profiles](https://www.government.nl/documents/publications/2019/02/05/climate-change-profiles)

### Further self-study resources:

* https://cran.r-project.org/web/packages/changepoint/changepoint.pdf
* https://www.youtube.com/watch?v=WelmlZK5G2Y&ab_channel=NHSRCommunityNHSRCommunity
* https://www.coursera.org/learn/machine-learning

  





```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```
