---
pagetitle: "Kamino"
output:
  bookdown::gitbook: default
documentclass: book
date: "`r Sys.Date()`"
---


```{r, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE,
   dev = "svg")
options(scipen=999)  # turn-off scientific notation like 1e+48

library(knitcitations)
library(bibtex)
library(changepoint)
library(tidyverse)
library(ggiraph)


```

ANALYTICS 


# Change
# Case: US Border Crossing Entry


***

# Load the data
```{r load-data, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}


df<-read_csv('archetypes/Border_Crossing_Entry_Data.csv')
df
```

# Wrangler the data

```{r message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-show'}

# Format date
df$newDate <- strptime(as.character(df$Date), "%m/%d/%Y")
df$newDate<-format(df$newDate, "%Y-%m-%d")

# Filter port and measure
df_elpaso<-df%>%
  filter(`Port Name` == "El Paso" & 
           Measure == 'Pedestrians')%>%
  select( newDate, Value)%>%
  arrange(newDate)

df_elpaso
```

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}
plot(df_elpaso$Value,type='l')

# Filter 2019 and 2020
df_2y <-df_elpaso%>%
  filter(newDate > '2018-12-31')
```

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}

plot(df_2y$Value,type='l',xlab='Month',ylab='Number of Pedestrians')

# Check the standard deviation
sd(df_2y$Value)


```

# Single Change in Mean

```{r echo=TRUE, message=FALSE, warning=FALSE, class.source='fold-hide'}

df_2y_scale<- as.vector(scale(df_2y$Value))


```

## At most one change

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}

# Default method is AMOC
df_2y.amoc=cpt.mean(df_2y_scale)
cpts(df_2y.amoc)

plot(df_2y.amoc,xlab='Month',ylab='Scaled sd to 1')

```



# Multiple Changes in Mean and Variance

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}


df_elpaso.pelt=cpt.meanvar(df_elpaso$Value,
      method='BinSeg',Q=20,penalty="SIC")
cpts(df_elpaso.pelt) # 20  53  69  96 164 180 234 272

paste0('Change Point 1: ',df_elpaso$newDate[20])
paste0('Change Point 2: ',df_elpaso$newDate[53])
paste0('Change Point 3: ',df_elpaso$newDate[69])
paste0('Change Point 4: ',df_elpaso$newDate[96])
paste0('Change Point 5: ',df_elpaso$newDate[164])
paste0('Change Point 6: ',df_elpaso$newDate[180])
paste0('Change Point 7: ',df_elpaso$newDate[234])
paste0('Change Point 8: ',df_elpaso$newDate[272])


param.est(df_elpaso.pelt)
plot(df_elpaso.pelt,cpt.width=1,cpt.col='red')
abline(v=69, col="blue")
```




# References
## The data source is from [kaggle](https://www.kaggle.com/divyansh22/us-border-crossing-data)

## Further self-study resources:

* https://cran.r-project.org/web/packages/changepoint/changepoint.pdf
* https://www.youtube.com/watch?v=WelmlZK5G2Y&ab_channel=NHSRCommunityNHSRCommunity
* https://www.coursera.org/learn/machine-learning

