---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs

---


```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE,
   dev = "svg")
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memory and report the memory usage.

library(knitcitations)
library(bibtex)
library(changepoint)
library(tidyverse)
library(ggiraph)


```

<div class="activity">
ANALYTICS 
</div>

# Change
# Case: US Border Crossing Entry


***

# Load the data
```{r load-data, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}


df<-read_csv('archetypes/Border_Crossing_Entry_Data.csv')
df
```

# Wrangler the data

```{r message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-show'}

# Format date
df$newDate <- strptime(as.character(df$Date), "%m/%d/%Y")
df$newDate<-format(df$newDate, "%Y-%m-%d")

# Filter port and measure
df_elpaso<-df%>%
  filter(`Port Name` == "El Paso" & 
           Measure == 'Personal Vehicle Passengers')%>%
  select( newDate, Value)%>%
  arrange(newDate)

df_elpaso


```


# Single Change in Mean

## Scale std to 1

```{r echo=TRUE, message=FALSE, warning=FALSE, class.source='fold-hide'}

df_scale<- as.vector(scale(df_elpaso$Value))


```

## At most one change

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}

# Default method is AMOC
df.amoc=cpt.mean(df_scale)
cpts(df.amoc)

plot(df.amoc,xlab='Month',ylab='Scaled sd to 1')
abline(v=68, col="blue")
paste0('Change Point 1: ',df_elpaso$newDate[68])

```

# Multiple Changes in Variance

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}

df_elpaso.var=cpt.var(df_elpaso$Value, method='BinSeg', penalty='Manual', pen.value='2*log(nrow(df_elpaso))')

cpts(df_elpaso.var) #68 137

paste0('Change Point 1: ',df_elpaso$newDate[68])
paste0('Change Point 2: ',df_elpaso$newDate[137])


param.est(df_elpaso.var)
plot(df_elpaso.var,cpt.width=1,cpt.col='blue')
```



# Multiple Changes in Mean and Variance

```{r echo=TRUE, fig.height=6, fig.width=12, message=FALSE, warning=FALSE, class.source='fold-hide'}


df_elpaso.pelt=cpt.meanvar(df_elpaso$Value,
      method='PELT',penalty="SIC")
cpts(df_elpaso.pelt) # 2  40  48  50  64  68  88 135 137 156 178 201 203 218 254 275 277

paste0('Change Point 17: ',df_elpaso$newDate[277])



param.est(df_elpaso.pelt)
plot(df_elpaso.pelt,cpt.width=1,cpt.col='red')
abline(v=277, col="blue")
abline(v=68, col="blue")
```




# References
## The data source is from [kaggle](https://www.kaggle.com/divyansh22/us-border-crossing-data)



  





```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```
