---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999) # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(stringr)
library(countrycode)
library(scales)
library(ggtern)
library(ggiraph)

# needed to include bib references
library(knitcitations)
library(bibtex)

library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Inconsolata", "inconsolata")
# turn on showtext
showtext_auto()

```

<div class="activity">
CHARTS
</div>

# Gapminder
## Ternary

***

# Load the data [Ingest]

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Load data
df <- read.csv("archetypes/gapminder/gapminder-all-years.csv", header = TRUE, stringsAsFactors = FALSE)
df

```

# Prepare the data [Wrangle]

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Enrich with continent using country code
df$continent <- countrycode(df$country_code, origin = 'iso3c', destination = 'continent')

# Filter for single year
gapminder <- filter(df, year == 2020)

# Remove cases with NA
gapminder <- gapminder[complete.cases(gapminder), ]

# Rescale 0 to 100
gapminder$gdp <- rescale(gapminder$gdp, to=c(0,100))
gapminder$lex <- rescale(gapminder$lex, to=c(0,100))
gapminder$pop <- rescale(gapminder$pop, to=c(0,100))

gapminder

```

# Plot the chart
## USDA National Nutrient Database

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=13, fig.height=24, out.width = "100%"}

continent_palette <- c("Africa" = "#77dff7", "Americas" = "#b5ea32", "Asia" = "#ff5973", "Europe" = "#ffe800", "Oceania" = "#ff5973")

theme_opts <- theme(
  legend.position = "bottom",
  legend.title = element_blank(),
  tern.axis.title.L = element_text(hjust = 0.5),
  tern.axis.title.R = element_text(hjust = 0.5),
  panel.background = element_blank(),
  panel.border = element_blank(),
  plot.background = element_blank(),
  plot.margin = unit(c(0, 0, 0, 0), "in")
)

v1 <- ggtern(data=gapminder, aes(gdp, lex, pop)) + 
  geom_point(aes(color = continent), size = 2.5, alpha=.6) + 
  scale_color_manual(values = continent_palette) +
  coord_tern() +
  theme_minimal() +
  theme_nomask() +
  theme_opts +
  labs(title = "Gapminder", 
           subtitle = "2020") +
           xlab("gdp") + 
           ylab("life expectancy") +
           zlab("population") +
  facet_wrap(~ continent, ncol = 1)

girafe(ggobj = v1, width_svg = 13, height_svg = 24,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```


```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-show'}

# eval = FALSE as default; run manually as chunk

# full version
ggsave(filename = "assets/usda-food-data-fs.svg", plot = v1, width=1280/72, height=720/72)

# without annotations
ggsave(filename = "assets/usda-food-data-sm.svg", plot = v1, width=4, height=2.25)

```


# References
## The citations and data sources used for this case


```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

cleanbib()
options("citation_format" = "pandoc")
#read.bibtex(file = "../archetypes/...bib")

```


```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-hide'}

# eval = FALSE as default; run manually as chunk

# ENTER METADATA
# Use space to separate keywords or "-" for phrases
methods <- "" # mostly used in wranglers and analytics
keywords <- 'food protein carbohydrates fat'
commands <- 'ggtern coord_tern'
sources <- 'USDA'

# CREATE METADATA
source("../../../z-scripts/create_metadata.R", local = knitr::knit_global())

# RUN PRODUCTION OUTPUTS
source("../../../z-scripts/create_production_output.R", local = knitr::knit_global())


```


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

