{
  '18': [
      ["food",0.5,0,"Drinking"],
      ["sleep",7.5,0.5,"Sleep"],
      ["food",1.5,8,"Grapefruit, cereal, banana, tea"],
      ["creative",3.5,9.5,"He would pick up from where he left off the previous evening"],
      ["food",3.5,13,"Lunch at the pub with a drink before and a coffee after"],
      ["sleep",0.5,16.5,"Nap in his favorite armchair"],
      ["creative",2,17,"Main work"],
      ["food",4,19,"Dinner with family, drinking scotch and water whilst settling down to his favorite television programs"],
      ["food",1,23,"Final scotch and water"]
    ],
   '7': [
      ["sleep",5.5,0,"Sleep"],
      ["other",0.5,5.5,"Getting dressed"],
      ["food",0.5,6,"Coffee with husband"],
      ["other",0.5,6.5,"Commute to hotel room she rented for work"],
      ["creative",8,7,"Writing in hotel room, the more anonymous the better"],
      ["food",4.5,15,"Shower, cook, have dinner with husband"],
      ["creative",0.5,19.5,"Reading work to husband"],
      ["food",2,20,"Time with husband"],
      ["sleep",2,22,"Sleep"]
    ],
    '8': [
      ["sleep",5.5,0,"Sleep"],
      ["food",0.5,5.5,"Coffee with a crossword"],
      ["creative",5,6,"Worked with a dose of Benzedrine, a daily routine he kept up for 20 years"],
      ["food",0.5,11,"Lunch"],
      ["creative",6.5,11.5,"Main work"],
      ["food",1.5,18,"Strong vodka martinis"],
      ["food",2.5,19.5,"Dinner with friends"],
      ["sleep",2,22,"Used sedative to go to sleep"]
    ],
    '0': [
      ["sleep",1,0,"Sleep"],
      ["creative",7,1,"Wore monkish robe and Moroccan slippers for his priest-like work"],
      ["sleep",1.5,8,"Nap"],
      ["creative",6,9.5,"Had a cup of black coffee before starting work"],
      ["food",2.5,15.5,"Received friends, took a bath, went out for dinner"],
      ["sleep",6,18,"Sleep"]
    ],
    '9': [
      ["sleep",6,0,"Sleep"],
      ["food",0.5,6,"Just a coffee, 60 beans per cup "],
      ["creative",8,6.5,"Worked on compositions at his desk, taking the occasional break to walk outdoors, which aided his creativity"],
      ["food",1,14.5,"Dinner with wine"],
      ["exercise",1,15.5,"Long walk"],
      ["food",4,16.5,"Tavern to eat and to read a newspaper"],
      ["food",1,20.5,"Supper"],
      ["sleep",2.5,21.5,"Sleep"]
    ],
    '10': [
      ["sleep",6,0,"Sleep"],
      ["food",1,6,"Praying, having coffee"],
      ["food",2,7,"Church"],
      ["creative",3,9,"Work"],
      ["food",9,12,"Hobbies, guests, painting, taking care of birds"],
      ["sleep",3,21,"Sleep"]
    ],
    '11': [
      ["sleep",6,0,"Sleep"],
      ["exercise",0.5,6,"Preparing mind and body for the day ahead"],
      ["food",2.5,6.5,"Breakfast with wife"],
      ["creative",5.5,9,"Painting, drawing, writing"],
      ["admin",3,14.5,"Office hours (getting others to work on his ideas)"],
      ["food",5.5,17.5,"Time at home"],
      ["sleep",1,23,"Sleep"]
    ],
    '14': [
      ["sleep",7,0,"Sleep"],
      ["exercise",0.5,7,"Walk"],
      ["food",0.5,7.5,"Breakfast"],
      ["creative",1.5,8,"Focused work"],
      ["admin",1,9.5,"Reading mail"],
      ["creative",1.5,10.5,"Work"],
      ["exercise",0.5,12,"Walking the dog"],
      ["food",0.5,12.5,"Lunch"],
      ["admin",1,13,"Reading newspapers"],
      ["admin",1,14,"Writing letters"],
      ["sleep",1,15,"Nap"],
      ["exercise",0.5,16,"Walk"],
      ["admin",1,16.5,"Admin bits and bobs"],
      ["food",0.5,17.5,"Idleness"],
      ["food",1,18,"Reading for pleasure"],
      ["food",1,19,"Tea with egg"],
      ["food",1,20,"Playing backgammon"],
      ["admin",1,21,"Reading science books"],
      ["creative",2,22,"Lying in bed, solving problems"]
    ],
    '15': [
      ["sleep",7,0,"Sleep"],
      ["other",1,7,"Waking up"],
      ["food",1,8,"Breakfast"],
      ["creative",5,9,"Writing in absolute quiet"],
      ["exercise",3,14,"Walking around London"],
      ["food",1,17,"Gap time"],
      ["food",1,18,"Dinner"],
      ["food",5,19,"Time with friends and family"]
    ],
    '23': [
      ["creative",3,0,"Writing"],
      ["sleep",7,3,"Sleep"],
      ["admin",0.5,10,"Newspapers, mail"],
      ["other",0.5,10.5,"Taking a bath"],
      ["food",1,11,"Light breakfast, typically eggs, vegetables, cheese or fruit and a cup of cold chocolate"],
      ["exercise",1,12,"Outdoor stroll with family"],
      ["admin",1,13,"Teaching history"],
      ["creative",5,14,"Creative work, mostly reading"],
      ["food",1,19,"Dinner with family"],
      ["food",1.5,20,"Time with family, talking to mother"],
      ["creative",2.5,21.5,"Creative work"]
    ],
    '4': [
      ["sleep",5,0,"Sleep"],
      ["food",3,5,"Wash, make a resolution, have breakfast"],
      ["creative",4,8,"Work"],
      ["food",2,12,"Reading, life admin, lunch"],
      ["creative",4,14,"Work"],
      ["food",4,18,"Supper, music, putting things in order, socialising"],
      ["sleep",2,22,"Sleep"]
    ],
    '16': [
      ["creative",1,0,"Writing"],
      ["sleep",6,1,"Sleep"],
      ["food",1,7,"Breakfast and trimming beard"],
      ["creative",4,8,"Treating patients"],
      ["food",1,12,"Gap time"],
      ["food",1,13,"Lunch"],
      ["exercise",1,14,"Speedy walk"],
      ["creative",6,15,"Consulting and treating patients"],
      ["food",1.5,21,"Supper and card games"],
      ["creative",1.5,22.5,"Reading and writing"]
    ],
    '12': [
      ["sleep",6,0,"Sleep"],
      ["food",0.5,6,"Coffee and two raw eggs"],
      ["creative",4.5,6.5,"Writing"],
      ["other",1,11,"Ice bath on the roof"],
      ["food",1,12,"Guests and lunch"],
      ["exercise",2,13,"Long, strenuous exercise"],
      ["other",1,15,"Visit to the barber"],
      ["food",2,16,"Date"],
      ["creative",2,18,"Writing"],
      ["food",2,20,"Dinner, playing cards, going out"],
      ["sleep",2,22,"Sleep"]
    ],
    '22': [
      ["creative",6,0,"Writing"],
      ["sleep",2.5,6,"Sleeping after struggling to fall asleep"],
      ["admin",6,8.5,"Work at the worker's accident insurance institute"],
      ["food",1,14.5,"Lunch"],
      ["sleep",4,15.5,"Catching up on sleep"],
      ["exercise",1.5,19.5,"Exercises next to the window, then a walk"],
      ["food",2,21,"Dinner with family"],
      ["creative",1,23,"Writing"]
    ],
    '5': [
      ["sleep",5,0,"Sleep"],
      ["food",1,5,"Tea and pipe"],
      ["creative",1,6,"Writing"],
      ["admin",4,7,"Lecturing at the university"],
      ["food",4,11,"Meat and wine at the pub for lunch, main meal of the day"],
      ["exercise",1,15,"Walk"],
      ["creative",3,16,"Working with Joseph Green"],
      ["food",3,19,"Reading"],
      ["sleep",2,22,"Sleep"]
    ],
    '19': [
      ["sleep",8,0,"Sleep"],
      ["other",1,8,"Taking a bath"],
      ["creative",3,9,"Writing"],
      ["food",0.5,12,"Lunch"],
      ["creative",3.5,12.5,"Reading"],
      ["sleep",1,16,"Nap"],
      ["food",0.5,17,"Tea with family"],
      ["admin",1.5,17.5,"Reading newspapers, mail"],
      ["exercise",0.5,19,"Walk"],
      ["food",4.5,19.5,"Time with family, guests, listening to music"]
    ],
    '1': [
      ["sleep",4,0,"Sleep"],
      ["other",1,4,"Meditation"],
      ["food",2,5,"Listening to aide reading bible"],
      ["creative",3,7,"Dictating to aide"],
      ["creative",2,10,"Listening to aide read back"],
      ["food",1,12,"Lunch"],
      ["exercise",3,13,"Walk up and down his garden"],
      ["food",5,16,"Having guests over, supper, smoking a pipe"],
      ["sleep",3,21,"Sleep"]
    ],
    '13': [
      ["creative",1,0,"Composing"],
      ["sleep",5,1,"Sleep"],
      ["other",1,6,"Getting dressed"],
      ["creative",2,7,"Composing"],
      ["admin",4,9,"Giving music lessons"],
      ["food",4,13,"Lunch with friends"],
      ["creative",4,17,"Composing or giving concerts"],
      ["food",2,21,"Time with friends"],
      ["creative",1,23,"Composing"]
    ],
    '2': [
      ["sleep",4,0,"Sleep"],
      ["creative",8,4,"Writing"],
      ["exercise",1,12,"Walking and swimming"],
      ["food",8,13,"Doing housework, admin and spending time with family"],
      ["sleep",3,21,"Sleep"]
    ],
    '17': [
      ["sleep",1,0,"Trying to fall sleep"],
      ["sleep",6.5,1,"Sleep"],
      ["food",1,7.5,"Thinking in bed"],
      ["food",1.5,8.5,"Shave, breakfast, meditation, bath"],
      ["creative",1,10,"Writing"],
      ["exercise",0.5,11,"Walk"],
      ["creative",1.5,11.5,"Work"],
      ["food",1,13,"Lunch"],
      ["creative",4.5,14,"Writing"],
      ["exercise",0.5,18.5,"Walk"],
      ["food",2,19,"Time with family"],
      ["creative",2.5,21,"Reading"],
      ["sleep",0.5,23.5,"Trying to sleep"]
    ],
    '24': [
      ["creative",2.5,0,"Painting"],
      ["sleep",8.5,2.5,"Sleep"],
      ["food",4,11,"Breakfast, seeing friends"],
      ["creative",7.5,15,"Painting"],
      ["food",1,22.5,"Dinner"],
      ["creative",0.5,23.5,"Painting"]
    ],
    '20': [
      ["sleep",8,0,"Sleep"],
      ["food",1.5,8,"Breakfast of 3 eggs, tea, and jam; bath"],
      ["exercise",0.5,9.5,"Walk"],
      ["creative",3,10,"Composing"],
      ["food",1,13,"Lunch with friends"],
      ["food",1,14,"Reading or playing games"],
      ["creative",1,15,"Composing"],
      ["food",1,16,"Dinner and tea"],
      ["exercise",1,17,"Walk"],
      ["admin",1,18,"Writing letters"],
      ["food",2.5,19,"Dinner and socialising"],
      ["food",0.5,21.5,"Reading for pleasure"],
      ["sleep",2,22,"Sleep"]
    ],
    '25': [
      ["food",1,0,"Up at night"],
      ["food",2,1,"Listening to music, drinking, smoking"],
      ["sleep",9,3,"Sleep"],
      ["food",1.5,12,"Reading and thinking in bed"],
      ["food",1,13.5,"Lunch"],
      ["admin",1.5,14.5,"Errands, mail"],
      ["creative",4,16,"Writing"],
      ["food",4,20,"Dinner with family, then listening to music, drinking, smoking"]
    ],
    '21': [
      ["sleep",8,0,"Sleep"],
      ["food",1,8,"Tea, smoking, reading bible and philosophy"],
      ["exercise",0.5,9,"Walk"],
      ["admin",0.5,9.5,"Mail"],
      ["creative",2,10,"Composing"],
      ["food",1,12,"Lunch"],
      ["exercise",2,13,"Long walk"],
      ["food",2,15,"Tea, reading newspapers"],
      ["creative",2,17,"Composing"],
      ["other",1,19,"Gap time"],
      ["food",4,20,"Dinner, having guests, socialising"]
    ],
    '3': [
      ["sleep",4,0,"Sleep"],
      ["creative",8,4,"Working in bed, dictating his thoughts to a secretary"],
      ["other",0.5,12,"Getting dressed"],
      ["creative",1.5,12.5,"Working"],
      ["admin",2,14,"Surveying the estate with secretary"],
      ["creative",4,16,"Working"],
      ["food",1.5,20,"Dinner with family"],
      ["creative",2.5,21.5,"Working"]
    ],
    '6': [
      ["sleep",5.5,0,"Sleep"],
      ["creative",2.5,5.5,"Writing"],
      ["food",0.5,8,"Breakfast"],
      ["creative",1.5,8.5,"Writing"],
      ["exercise",1.5,10,"Walk, swim"],
      ["food",1,11.5,"Lunch"],
      ["admin",5,12.5,"Teaching at school"],
      ["food",4.5,17.5,"Drinking scotch, making supper, listenting to jazz"],
      ["sleep",2,22,"Sleep"]
  ]
}