---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(ggiraph)

```

<div class="activity">
MAPS  
</div>

# World Tile Grid
## Temp



***

# Header
## Subheader

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

worldtilegrid <- read.csv("archetypes/world-tile-grid.csv", header = TRUE)
worldtilegrid

```


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=6}

mytheme <- theme_minimal() + theme(panel.grid = element_blank(), axis.text = element_blank(), axis.title = element_blank())
colors <- c("#7F3C8D","#11A579","#3969AC","#F2B701","#E73F74","#80BA5A")

v1 <- ggplot(worldtilegrid, aes(xmin = x, ymin = y, xmax = x + 1, ymax = y + 1, fill = region)) +
  geom_rect(color = "#ffffff") +
  geom_text(aes(x = x, y = y, label = alpha.2), color = "#ffffff", alpha = 0.5, nudge_x = 0.5, nudge_y = -0.5, size = 3) + 
  scale_y_reverse() + 
  scale_fill_manual(values = colors) + 
  coord_equal() +
  mytheme + theme(legend.position = "bottom")

girafe(ggobj = v1, width_svg = 13, height_svg = 10,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```

# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case

http://www.maartenlambrechts.com/2017/10/22/tutorial-a-worldtilegrid-with-ggplot2.html

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```




```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```