---
title: "Template"
output: 
  html_document:
    theme: flatly
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)

options(scipen=999)  # turn-off scientific notation like 1e+48

library(tidyverse)
library(tm)
library(methods) # quanteda
library(topicmodels)

```


## Parameters


```{r, echo=FALSE}

focus_question <- 11
question_language <- "en"

question_list <- read.csv("list-of-questions.csv", header = TRUE, stringsAsFactors = FALSE, encoding="UTF-8")
question_list

question_filter <- filter(question_list, QID == focus_question)
question_filter$Question


```


## Ingest Text


```{r}

data_file <- paste0("./outputs/q-", focus_question, "-lang.csv")

corpus_csv <- read.csv(data_file, header = TRUE, stringsAsFactors = FALSE, encoding="UTF-8")

# Filter english
corpus_csv <- filter(corpus_csv, cld2 == question_language)
corpus_csv

```

## Topic Models

```{r, fig.width=7, fig.height=10}

corpus_dfm <- Corpus(VectorSource(corpus_csv$Comment))

corpus_dtm <- DocumentTermMatrix(corpus_dfm, control = list(removePunctuation = TRUE, stopwords = TRUE))
raw.sum=apply(corpus_dtm,1,FUN=sum) #sum by raw each raw of the table
corpus_dtm <- corpus_dtm[raw.sum!=0,]
inspect(corpus_dtm)

ap_lda <- LDA(corpus_dtm, k = 2, control = list(seed = 1234))
ap_lda

ap_topics <- tidy(ap_lda, matrix = "beta")
ap_topics

ap_top_terms <- ap_topics %>%
group_by(topic) %>%
top_n(10, beta) %>%
ungroup() %>%
arrange(topic, -beta)
ap_top_terms %>%
mutate(term = reorder(term, beta)) %>%
ggplot(aes(term, beta, fill = factor(topic))) +
geom_col(show.legend = FALSE) +
facet_wrap(~ topic, scales = "free") +
coord_flip()

beta_spread <- ap_topics %>% mutate(topic = paste0("topic", topic)) %>%
  spread(topic, beta) %>% filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1))
beta_spread

# Document-Topic Probabilities
ap_documents <- tidy(ap_lda, matrix = "gamma")
ap_documents

tidy(corpus_dtm) %>% filter(document == 6) %>% arrange(desc(count))

```



