---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation


library(tidyverse)
library(ggTimeSeries)

library(htmltools) # needed to include html snippets
library(knitcitations)
library(bibtex)

```

<div class="activity">
TEMPORALS
</div>

# Streamgraph
## Nuclear warheads by country

***

# Section
## Subsection

```{r, echo=FALSE}

df <- read.csv("archetypes/number-of-nuclear-warheads-in-the-inventory-of-the-nuclear-powers.csv", header = TRUE, stringsAsFactors = TRUE)
df

```

# Section
## Subsection


```{r, echo=FALSE, fig.width=12, fig.height=6}

theme_opts <- theme(
  legend.position = "bottom",
  legend.title = element_blank(),
  axis.text.y = element_blank(),
  axis.line.y = element_blank(),
  axis.ticks.y = element_blank(),
  axis.title.y = element_blank(),
  # panel.grid = element_blank(),
  # panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

code_pal <- c("CHN" = "#ef5350", 
              "GBR" = "#0D47A1",
              "ISR" = "#FFA000",
              "PAK" = "#388E3C",
              "USA" = "#0288D1",
              "FRA" = "#00BCD4",
              "IND" = "#EF6C00",
              "RUS" = "#c62828")

v1 <- ggplot(df, aes(x = Year, y = N, group = Code, fill = Code, color = Code)) +
  stat_steamgraph() +
  scale_x_continuous(breaks = c(1950, 1960, 1970, 1980, 1990, 2000, 2010)) +
  scale_color_manual(values = code_pal ) +
  scale_fill_manual(values = code_pal ) +
  theme_minimal() +
  theme_opts +
  xlab(NULL) +
  ylab(NULL)

v1

```

# Section
## Subsection


```{r, echo=FALSE}

# ggsave(filename = "stream-nuclear-weapon-stockpiles.svg", plot = v1, width=12, height=6)
# ggsave(filename="stream-nuclear-weapon-stockpiles.png", plot=v1, device="png", height=12, width=6, units="in", dpi=500)

```



# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case

Source:  FAS Nuclear Notebook

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

