---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/kamino.css", "../../../z-assemblers/diagrams.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/header.html"
      after_body: "../../../z-assemblers/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

library(htmltools) # needed to include html snippets
library(tidyverse)
library(DiagrammeR)
library(causalloop)

library(knitcitations)
library(bibtex)

```

<div class="activity">
DIAGRAMS
</div>

# Mind map
## I want to fix irregularities in my dataset

> Don't call the world dirty because you forgot to clean your glasses...\
--- Aaron Hill\



***

# Section
## Subsection

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

L <- CLD(from     = c("a","a","b","c","d","d","e"),
         to       = c("b","c","a","d","b","a","d"),
         polarity = c(1,1,-1,-1,1,-1,1)) %>%
  addNodeData(tibble::tibble(node="c", group="core")) %>%
  addNodeGroup("core", fontcolor="red", color="yellow")
plot(L)
plot(L, nodes=c("c"))

```


```{r}



```


```{r}



```




```{r}



```


```{r}



```



# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```


```{r, message=FALSE, warning=FALSE, echo=FALSE}

# echo=FALSE will exclude block from code folding
# Example for including external html content when needed
htmltools::includeHTML("mark-complete-button.html")

```



```{r, child='mark-complete-click.Rmd'}

# JS event handler for button click

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

