---
pagetitle: "Energy Forecast"
output:
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: ["../../../z-assemblers/fragments/google-analytics.html", "../../../z-assemblers/fragments/header.html"]
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)

library(tidyverse)
library(jsonlite)
library(plotly)
library(networkD3)

```

<div class="activity">
GRAPHS  
</div>

# Energy Forecast 2050
## Sankey

***

### Load data [Ingest]


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Flatten for easy access to properties
plotly_graph <- fromJSON('archetypes/energy-forecast/sankey_energy.json', flatten = TRUE)[[1]]
head(plotly_graph, n=10)

d3_graph <- fromJSON("archetypes/energy-forecast/energy.json")
# d3_graph

```


### Plotly Version


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source ='fold-hide', out.width="100%", fig.height=8}

node_labels <- unlist(plotly_graph$node.label)
node_color <- unlist(plotly_graph$node.color)

link_source <- unlist(plotly_graph$link.source)
link_target <- unlist(plotly_graph$link.target)
link_value <- unlist(plotly_graph$link.value)
link_label <- unlist(plotly_graph$link.label)

fig <- plot_ly(
  type = "sankey",
  domain = list(
    x =  c(0,1),
    y =  c(0,1)
  ),
  orientation = "h",
  valueformat = ".0f",
  valuesuffix = "TWh",
  
  node = list(
    label = node_labels,
    color = node_color,
    pad = 15,
    thickness = 15,
    line = list(
      color = "black",
      width = 0.5
    )
  ),
  
  link = list(
    source = link_source,
    target = link_target,
    value =  link_value,
    label =  link_label
  )
) 
fig <- fig %>% layout(
  title = "Energy forecast for 2050<br>Source: Department of Energy & Climate Change, Tom Counsell via Mike Bostock",
  font = list(
    size = 10
  ),
  xaxis = list(showgrid = F, zeroline = F),
  yaxis = list(showgrid = F, zeroline = F)
)

fig

```


### Network D3 Version


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source ='fold-hide', out.width="100%", fig.height=8}

# Convert to data frame
EngNodes <- d3_graph$nodes
EngLinks <- d3_graph$links

# EngNodes
# EngLinks

# Plot
sankey <- sankeyNetwork(Links = EngLinks, Nodes = EngNodes, Source = "source",
         Target = "target", Value = "value", NodeID = "name",
         units = "TWh", fontSize = 12, nodeWidth = 30)

sankey

# saveNetwork(sankey, file = "energy.html", selfcontained = TRUE)

```


### References
#### citations for narrative and data sources


```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-hide'}

# eval = FALSE as default; run manually as chunk
# PUSH TO PRODUCTION
source("../../../z-scripts/create_production_output.R", local = knitr::knit_global())

```


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```



