---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(dplyr)
library(stringr)
library(ggplot2)
library(maps)

```

<div class="activity">
MAPS  
</div>

# Choropleth Map
## Load Data Sources

* World Map
* What makes a good government

***

# Section
## Subsection

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

world <- map_data("world")
# head(world)

worldgovt <- read.csv("archetypes/what-makes-a-good-government.csv", header = TRUE)
worldgovt <- dplyr::select(worldgovt, region = indicator, "HDI" = `human.development.index`, "CC" = ISO.Country.code)
worldgovt

```

# Section
## Subsection

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

## Check for disagreements between the two datasets
diff <- setdiff(world$region, worldgovt$region)

## Clean the dataset accordingly
worldgovt <- worldgovt %>%
  ## Recode certain entries
  mutate(region = recode(str_trim(region), "United States" = "USA",
                            "United Kingdom" = "UK",
                            "Korea (Rep.)" = "South Korea",
                            "Congo (Dem. Rep.)" = "Democratic Republic of the Congo",
                            "Congo (Rep.)" = "Republic of Congo")) %>%
  ## Editing the "North Korea" entry is a little trickier for some reason
  mutate(region = case_when((CC == "PRK") ~ "North Korea",
                               TRUE ~ as.character(.$region)))

## Make the HDI numeric
worldgovt$HDI <- as.numeric(as.character(worldgovt$HDI))

worldSubset <- inner_join(world, worldgovt, by = "region")
head(worldSubset)

```

# Section
## Subsection

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=12}

## theme parameters
plain <- theme(
  legend.position="bottom",
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "white"),
  plot.title = element_text(hjust = 0.5)
)

worldHDI <- ggplot(data = worldSubset, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) +
  geom_polygon(aes(fill = HDI), color="white") +
  scale_fill_distiller(palette ="RdBu", direction = 1)
  ggtitle("Global Human Development Index (HDI)") +
  plain

worldHDI

```



```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

ggsave(filename = "assets/what-makes-a-good-government.svg", plot = worldHDI, width=12, height=6)

```


# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case



```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


