---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(dplyr)
library(ggplot2)
library(ggiraph)

library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS
</div>

### Bar Horizontal Stacked : Environmental impact of food by life cycle stage

<a href="https://ourworldindata.org/food-choice-vs-eating-local">Article and Data Source</a>

```{r, echo=FALSE}

# Load data
df = read.csv("./archetypes/environmental-impact-of-food-by-life-cycle-stage.csv", header = TRUE, stringsAsFactors = TRUE)
# To sort stacked bars by stage of supply chain
df$SUPPLY_CHAIN <- factor(df$SUPPLY_CHAIN, levels=rev(c("Land use change", 
                          "Farm", 
                          "Animal Feed", 
                          "Processing", 
                          "Transport", 
                          "Retail",
                          "Packging")))

df

# create summary label for each stack
total_labels <- df %>%
    group_by(FOOD_PRODUCT) %>%
    summarize(TOTAL = round(sum(EMISSION), digits=1))

```



```{r, echo=FALSE, fig.width=10.5, fig.height=7.5}

# as defined in imitated view
supply_chain_palette <- c("Land use change" = "#1ea349", 
                          "Farm" = "#a3745e", 
                          "Animal Feed" = "#f36e32", 
                          "Processing" = "#417aac", 
                          "Transport" = "#f04b54", 
                          "Retail" = "#f3ca19",
                          "Packging" = "#bcb0ac")

# reorder to sort by Food Product and Emission
# group to maintain stack sort
v1 = ggplot(df, aes(x=EMISSION, y=reorder(FOOD_PRODUCT,EMISSION), fill=SUPPLY_CHAIN, group = SUPPLY_CHAIN)) + 
    geom_bar(width=0.8, position="stack", stat="identity", color="#777777" ) +
    scale_fill_manual(values=supply_chain_palette) +
    scale_x_continuous(expand = c(0, 0)) +
    coord_cartesian(clip="off") +
    theme_bw() +
    theme(panel.border     = element_blank()) +
    theme(plot.background = element_blank()) +
    theme(panel.background = element_blank()) +
    theme(panel.grid.major.x = element_blank()) +
    theme(panel.grid.minor.x = element_blank()) +
    theme(panel.grid.major.y = element_blank()) +
    theme(panel.grid.minor.y = element_blank()) +
    theme(legend.title = element_blank()) + # remove legend title)
    theme(legend.position = "top") +
    # increase margin for right label
    theme(plot.margin = margin(.25, 1, .25, .25, "cm")) +
    xlab("GHG Emissions per kilogram of food product\n(kg CO2 -equivalents per kg product") +
    ylab("") +
    labs(
      title = "Food: greenhouse gas emissions across the supply chain",
      caption = "Source: Our World in Data"
    ) +
    geom_text(data=total_labels, aes(x=TOTAL+0.5, y=FOOD_PRODUCT, label=TOTAL, fill = NULL, group = NULL), size=2.5, hjust="left" )

girafe(ggobj = v1, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```




```{r, echo=FALSE, fig.width=10.5, fig.height=7.5}

# With annotations
v2 <- v1 + 
  #annotate("text", x = 3.5, y = "Fish (wild catch)", label = "'Farm' emissions for wild fish refers to fuel used by fishing vessels.", hjust = "left", size = 2.5, fontface = 1) +
  annotate("text", x = 4.5, y = "Nuts", 
           label = "  Nuts have a negative land use change figure\n- because nut trees are currently replacing croplands;\n  carbon is stored in the trees.", 
           hjust = "left", vjust=0.45, size = 2.5, fontface = 1) +
  annotate("text", x = 4.5, y = "Peas", 
           label = "- Factors such as transport distance, retail, packaging,\n  or specific farm methods are often\n  small compared to importance of food type.", 
           hjust = "left", size = 2.5, fontface = 1) +
  annotate("text", x = 4.5, y = "Maize (Meal)", 
           label = "- CO2 emissions from most plant-based\n  products are as much as 10-50 times\n  lower than most animal-based products.", 
           hjust = "left", size = 2.5, fontface = 1) +
  annotate("text", x = 5.0, y = "Milk", 
           label = "Methane production from cows means dairy milk has significantly higher emissions than plant-based milks.", 
           hjust = "left", size = 2.5, fontface = 1) +
  annotate("text", x = 6, y = "Rice", label = "Flooded rice produces methane, which dominates on-farm emissions.", hjust = "left", size = 2.5, fontface = 1) +
  annotate("text", x = 10, y = "Pig Meat", 
           label = "Pigs and poultry are non-ruminant livestock so do not produce methane.\nThey have significant lower emissions than beef and lamb.", 
           hjust = "left", vjust=0.75, size = 2.5, fontface = 1) +
  annotate("text", x = 24, y = "Beef (dairy herd)", 
           label = "Dairy co-products means beef from dairy herds\nhas a lower carbon footprint than dedicated beef herds.", 
           hjust = "left", vjust=0.75, size = 2.5, fontface = 1) +
  annotate("text", x = 35, y = "Beef (beef herd)", 
           label = "Methane production from cows, and land conversion for grazing and animal feed\nmeans beef from dedicated beef herds has a very high carbon footprint.", 
           hjust = "left", vjust=1.35, size = 2.5, fontface = 1)

v2 <- v2 + geom_segment(aes(
    x=4.5,
    y="Cane Sugar",
    xend=4.5, 
    yend="Nuts"
    ),
    size=0.5
  )

girafe(ggobj = v2, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))


```



```{r, echo=FALSE}

# Save plot to svg file
# ggsave(filename = "environmental-impact-of-food-by-life-cycle-stage-v1.svg", plot = v1, width=24.5, height=13)
# ggsave(filename = "environmental-impact-of-food-by-life-cycle-stage-v2.svg", plot = v2, width=24.5, height=13)

```


# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case

Source: <a href="https://www.economist.com/graphic-detail/2019/08/23/which-countries-dominate-the-worlds-dinner-tables"> Which countries dominate the world’s dinner tables?</a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```



