---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["styles/kamino.css"]
    df_print: paged
    mathjax: NULL
    code_folding: hide
---

```{r setup, include = FALSE, results = "hide"}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(sf)
library(geojsonio)
library(ggplot2)
library(ggiraph)
library(viridis)

```



```{r, message = FALSE, warning = FALSE, echo = FALSE, results = "hide"}

# Load map sources
# Shape files and data
# ++++++++++++++++++++
# borders, adm0
# borders, adm1
# borders, adm2
# ++++++++++++++++++++

# Borders
state_boundaries <- st_read("map-sources/geojson/ss-state.geojson")
county <- st_read("map-sources/geojson/ss-county.geojson")
abeyi <- st_read("map-sources/geojson/ss-abeyi.geojson")

head(as.data.frame(state_boundaries))
head(as.data.frame(county))
head(as.data.frame(abeyi))

```


```{r, message = FALSE, warning = FALSE, echo = FALSE, results = "hide"}

# DATA SOURCES
human_rights_incidents = read.csv("data-sources/confidential/human-rights-incident-dataset.csv", header = TRUE, stringsAsFactors = FALSE)
human_rights_incidents

hri <- as.data.frame(unique(human_rights_incidents$Violations.simplified)) # Types.of.violation, Violations.simplified
hri

sage = read.csv("data-sources/confidential/sage-march-2021.csv", header = TRUE, stringsAsFactors = FALSE)
sage

conflict_data = read.csv("data-sources/open-source/events/conflict_data_ssd.csv", header = TRUE, stringsAsFactors = FALSE)
conflict_data

iati_activities = read.csv("data-sources/open-source/events/iati-activities.csv", header = TRUE, stringsAsFactors = FALSE)
iati_activities

qc_conflict = read.csv("data-sources/open-source/events/qc_conflict_data_ssd.csv", header = TRUE, stringsAsFactors = FALSE)
qc_conflict

```




```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=12, out.width = "100%"}

human_rights_incidents$Number.of.victims[is.na(human_rights_incidents$Number.of.victims)] <- 0

# theme parameters
theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # panel.background = element_blank(),
  panel.background = element_rect(fill = "#ffffff"),
  panel.border = element_blank(),
  # plot.background = element_blank(),
  plot.background = element_rect(fill = "#ffffff")
)

transparent_fill <- rgb(0, 0, 0, max = 255, alpha = 0, names = "transparent")

# In order of layer placement top -> down
v1 = ggplot() + 
  geom_sf(data = state_boundaries, color="#333333", fill = transparent_fill, size=1.0) +
  geom_sf(data = county, color="#333333", fill = transparent_fill, size=0.5) +
  geom_sf(data = abeyi, color="#333333", fill = transparent_fill, size=0.5, linetype = "dashed") +
  # geom_point( data = human_rights_incidents, aes(x = Long, y = Lat, color = Number.of.victims), size = 2, alpha = 0.8 ) +
  geom_point_interactive( data = human_rights_incidents, 
                          aes(x = Long, y = Lat, color = Number.of.victims, size = Number.of.victims,
                              tooltip = paste0("Number of victims: ", Number.of.victims, "\n",
                                               "Violation type: ", Types.of.violation, "\n",
                                               "Remarks: ", Remarks)), 
                              alpha = 0.4) +
  scale_size(range = c(1, 15)) +
  scale_color_gradient2(low = "yellow", mid = "orange", high = "red", midpoint = mean(human_rights_incidents$Number.of.victims)) +
  scale_x_continuous() +
  scale_y_continuous() +
  coord_sf() +
  theme_bw() +
  labs(x = NULL, # Longitude
       y = NULL, # Latitude
       title = NULL, 
       subtitle = NULL) +
  theme_opts

# v1

girafe( ggobj = v1, width_svg = 12, height_svg = 8, options = list( opts_sizing(rescale = TRUE, width = 0.9) ))

```



```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=12, out.width = "100%"}

# print(min(sage$LONGITUDE))
sage <- filter(sage, LONGITUDE > 1.0)

v2 = ggplot() + 
  geom_sf(data = state_boundaries, color="#333333", fill = transparent_fill, size=1.0) +
  geom_sf(data = county, color="#333333", fill = transparent_fill, size=0.5) +
  geom_sf(data = abeyi, color="#333333", fill = transparent_fill, size=0.5, linetype = "dashed") +
  # geom_point( data = sage, aes(x = LONGITUDE, y = LATITUDE), size = 2 , color = "red", alpha = 0.8 ) +
  geom_point_interactive( data = sage, 
                          aes(x = LONGITUDE, y = LATITUDE,
                              tooltip = paste0("Date: ", DATE, "\n",
                                               "Location: ", LOCATION, "\n",
                                               "Description: ", DESCRIPTION)), 
                              color = "orange", size = 2, alpha = 0.4) +
  scale_x_continuous() +
  scale_y_continuous() +
  coord_sf() +
  theme_bw() +
  labs(x = NULL, # Longitude
       y = NULL, # Latitude
       title = NULL, 
       subtitle = NULL) +
  theme_opts

# v2

girafe( ggobj = v2, width_svg = 12, height_svg = 8, options = list( opts_sizing(rescale = TRUE, width = 0.9) ))

```


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=12, out.width = "100%"}

v3 = ggplot() + 
  geom_sf(data = state_boundaries, color="#333333", fill = transparent_fill, size=1.0) +
  geom_sf(data = county, color="#333333", fill = transparent_fill, size=0.5) +
  geom_sf(data = abeyi, color="#333333", fill = transparent_fill, size=0.5, linetype = "dashed") +
  geom_point( data = conflict_data, aes(x = longitude, y = latitude), size = 2 , color = "red", alpha = 0.8 ) +
  scale_x_continuous() +
  scale_y_continuous() +
  coord_sf() +
  theme_bw() +
  labs(x = NULL, # Longitude
       y = NULL, # Latitude
       title = NULL, 
       subtitle = NULL) +
  theme_opts

# v3

girafe( ggobj = v3, width_svg = 12, height_svg = 8, options = list( opts_sizing(rescale = TRUE, width = 0.9) ))

```


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=12, out.width = "100%"}

# Bounding box:  xmin: 24.15295 ymin: 3.504998 xmax: 35.94462 ymax: 12.23635

v4 = ggplot() + 
  geom_sf(data = state_boundaries, color="#333333", fill = transparent_fill, size=1.0) +
  geom_sf(data = county, color="#333333", fill = transparent_fill, size=0.5) +
  geom_sf(data = abeyi, color="#333333", fill = transparent_fill, size=0.5, linetype = "dashed") +
  geom_point( data = iati_activities, aes(x = location_longitude, y = location_latitude), size = 2 , color = "red", alpha = 0.8 ) +
  scale_x_continuous(limits = c(24.15295, 35.94462)) +
  scale_y_continuous(limits = c(3.504998, 12.23635)) +
  coord_sf() +
  theme_bw() +
  labs(x = NULL, # Longitude
       y = NULL, # Latitude
       title = NULL, 
       subtitle = NULL) +
  theme_opts

# v4

girafe( ggobj = v4, width_svg = 12, height_svg = 8, options = list( opts_sizing(rescale = TRUE, width = 0.9) ))

```



```{r, message = FALSE, warning = FALSE, echo = FALSE}

ggsave(filename = "assets/7-ssd-bubble-v1.svg", plot = v1, width=12, height=12)
ggsave(filename = "assets/7-ssd-bubble-v2.svg", plot = v2, width=12, height=12)
ggsave(filename = "assets/7-ssd-bubble-v3.svg", plot = v3, width=12, height=12)
ggsave(filename = "assets/7-ssd-bubble-v4.svg", plot = v4, width=12, height=12)

```


