---
title: "Dot Density"
output: 
  html_document:
    theme: flatly
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)

options(scipen=999)  # turn-off scientific notation like 1e+48

library(maptools)
library(sp)
library(sf)
library(rgdal)
library(raster)
library(rgeos)

library(tidyverse)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggthemes)

```

## Dot Density Map - Brazil

Source: <a href="https://www.worldpop.org/geodata/summary?id=44876">WorldPop</a>


```{r, message=FALSE, warning=FALSE, echo = FALSE}

city <- c('sao paulo','rio de janeiro','brasilia', "recife")
lat <- c(-23.473293, -22.9, -15.783333, -8.05)
long <- c(-46.665803,-43.233333,-47.916667, -34.9)
cities <- data.frame(city, lat, long)

bra_df <- read.csv("../archetypes/bra_pd_2020_1km_UNadj-normalized.csv", header = TRUE)

bra_df$x <- round(bra_df$x, digits=5)
bra_df$y <- round(bra_df$y, digits=5)

bra_df

```



```{r, echo=FALSE, fig.width=12, fig.height=6}

theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

# PLOT NATURAL EARTH BORDERS
ne_world <- ne_countries(scale = "small", returnclass = "sf")
# class(ne_world)

# Map only Brazil
ne_world <- filter(ne_world, iso_a3 == "BRA") 

v1 <- ggplot(data = ne_world) +
  geom_sf(fill="yellow", color="#666666", stroke=0.25) +
  geom_raster(data = bra_df,
              aes(x = x, y = y, fill = BIN, alpha = BIN) ) + 
  geom_point(data = cities, aes(x=long, y = lat ), color="#333333", size=1) +
  scale_fill_manual(values =  c("#A5D6A7", "#81C784", "#66BB6A", "#4CAF50", "#43A047", "#2E7D32", "#29296f"), guide = "none") +
  scale_alpha_manual(values =  c(0.9, 0.9, 0.9, 0.9, 0.9, 1.0, 1.0), guide = "none") +
  coord_sf() +
  theme_opts +
  labs(title = "Brazil",
         subtitle = "Population Density 2020 UN adjusted",
         caption = "worldpop.org"
       )

v1

```



```{r, echo=FALSE}

ggsave(filename = "world-pop-brazil.svg", plot = v1, width=12, height=6)
# ggsave(filename="livestock-sheep.png", plot=v1, device="png", width=12, height=6, units="in", dpi=500)

```

