---
title: "Dot Density"
output: 
  html_document:
    theme: flatly
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)

library(maptools)
library(sp)
library(sf)
library(rgeos)
library(tidyverse)
library(rgdal)
library(ggthemes)

```

## Dot Density Map - UK Census

Note: 1 dot = 10 people

Source: https://www.nomisweb.co.uk/census/2011/ks201ew


```{r, message=FALSE, warning=FALSE, echo = FALSE}

# ldnoa <- readOGR(dsn = "../archetypes/statistical-gis-boundaries-london/OA_2011_London_gen_MHW.shp") %>% spTransform(CRS("+proj=longlat +datum=WGS84"))
ldnb <- readOGR(dsn = "../archetypes/statistical-gis-boundaries-london/London_Borough_Excluding_MHW.shp") %>% spTransform(CRS("+proj=longlat +datum=WGS84"))

ldneth <- read.csv("../archetypes/london-ethnic-census.csv", stringsAsFactors=F, check.names=F)
ldneth

```


```{r, echo=FALSE, fig.width=9, fig.height=9}

theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
)

# define a palette
pal <- c("White" = "#8dd3c7",
         "Asian" = "#ffffb3", 
         "Black" = "#fb8072", 
         "Mixed" = "#bebada", 
         "Other" = "#80b1d3")

v1 = ggplot() +
  geom_point(data = ldneth, aes(x, y, color=Ethnicity), size = 0.01, alpha = 0.7 ) +
  geom_path(data = ldnb, 
          aes(x = long, y = lat, group = group),
          color = '#777777', size = 0.25) +
  scale_color_manual(values = pal) +
	theme_map() +
	theme_opts +
	coord_map()

v1

```



```{r, echo=FALSE}

ggsave(filename = "uk-ethnic-census.svg", plot = v1, width=6, height=6)
ggsave(filename="uk-ethnic-census.png", plot=v1, device="png", height=6, width=6, units="in", dpi=500)

```

