---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) # will clear all objects including hidden objects.
gc() #free up memory and report the memory usage.

library(tidyverse)
library(dplyr)
library(janitor)
library(ggtext)
library(ggdist)
library(ggiraph)
library(forcats)
library(knitcitations)
library(bibtex)
library(tidytuesdayR)
library(tidyr)
library(ggplot2)

library(here)
library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Inconsolata", "inconsolata")
# turn on showtext
showtext_auto()

```

# Lollipop Radial
<div class="activity">
CHARTS  
</div>


***

### Ingest

```{r echo=TRUE, message=FALSE, warning=FALSE, class.source='fold-hide'}

tuesdata <- tt_load(2020, week = 32)

energy_types <- tuesdata$energy_types
energy_types
country_totals <- tuesdata$country_totals
country_totals
```


### Wrangle
#### Filter, select, groupby, calculate ...

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source ='fold-hide', fig.width=1920/72, fig.height=1080/72, out.width="100%"}

clean_energy2 <- 
  energy_types %>% 
  filter(level == "Level 1") %>% 
  select(country, country_name, type, amount = `2018`) %>% 
  mutate(country_name = case_when(
    country == "EL" ~ "Greece",
    country == "UK" ~ "United Kingdom",
    TRUE ~ country_name
  )) %>% 
  group_by(country) %>% 
  mutate(total = sum(amount)) %>% 
  filter(type != "Conventional thermal") %>% 
  mutate(
    clean_total = sum(amount),
    `%clean` = clean_total/total,
    `%type` = amount/total,
    over50perc = ifelse(`%clean` > 0.5, "Over 50% clean energy", "NA")
  ) %>% 
  ungroup() %>% 
  arrange(country_name)

clean_energy2
```


### View / Chart
#### Radial Lollipop



```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source ='fold-hide', fig.width=1920/72, fig.height=1280/72, out.width="100%"}
v1<-clean_energy2 %>% 
  ggplot(aes(reorder(country_name, -`%clean`), `%clean`)) +
  geom_hline(yintercept = 1, color = "grey70") +
  geom_hline(yintercept = 0, color = "grey70") +
  geom_segment(
    aes(x = reorder(country_name, -`%clean`), 
        xend = reorder(country_name, -`%clean`), 
        y = 0, 
        yend = 1.1),
    color = "grey75",
    size = 0.5,
    lty = 3
  ) +
  geom_segment(
    aes(x = reorder(country_name, -`%clean`), 
        xend = reorder(country_name, -`%clean`), 
        y = 0, 
        yend = `%clean`),
    color = "grey40"
  ) +
  geom_point(aes(size = `%clean`, fill = over50perc),
             shape = 21,
             color = "grey40",
             alpha = 0.8) +
  labs(
    x = NULL,
    y = NULL,
    title = "Clean energy in EU Countries 2018",
    subtitle = "Clean energy = Energy not produced by conventional thermal methods",
    caption = "@MaiaPelletier | #TidyTuesday | Data: Eurostat"
  ) +
  scale_fill_manual(values = c("#f0f0f0", "grey40"), 
                    breaks = c("Over 50% clean energy"),
                    labels = c("Over 50% clean"),
                    name = NULL) +
  scale_size(range = c(1, 4)) +
  scale_y_continuous(limits = c(-0.15, 1.1)) +
  guides(size = "none") +
  
  coord_polar(clip = "off") +
  theme(
    text = element_text(family = "Montserrat", size = 8),
    plot.margin = margin(0, 50, 0, 50),
    plot.title = element_text(hjust = 0.5, 
                              size = 14,
                              face = "plain",
                              family = "Lato",
                              margin = margin(10, 0, 10, 0)),
    plot.subtitle = element_text(hjust = 0.5, 
                                 size = 8,
                                 face = "italic"),
    plot.caption = element_text(size = 6, 
                                margin = margin(0, 0, 8, 0)),
    axis.text.y = element_blank(),
    axis.text.x = element_text(hjust = -1, size = 7),
    legend.position = c(0.05, 0.925),
    legend.margin = margin(0, 0, 0, 0),
    legend.box.margin = margin(2, 8, 2, 2),
    legend.background = element_blank(),
    legend.box.background = element_rect(color = "grey65", fill = "#F0F0F0"),
    legend.key = element_blank()
  )

girafe(ggobj = v1, width_svg = 1080/72, height_svg = 720/72,
       options = list(opts_sizing(rescale = TRUE, width = 0.9))
)

```


### References
#### citations for narrative and data sources

* [Data Source](https://github.com/thebioengineer/tidytuesdayR)

```{r, echo=FALSE, eval=FALSE, message=FALSE, warning=FALSE, class.source='fold-hide'}

# eval = FALSE as default; run manually as chunk

# ENTER METADATA
# Use space to separate keywords or "-" for phrases
#methods <- "" # mostly used in wranglers and analytics
keywords <- 'lollipop'
commands <- 'geom_point geom_hline geom_segment'
sources <- 'OurWorldInData'

# CREATE METADATA
source("../../../z-scripts/create_metadata.R", local = knitr::knit_global())

# RUN PRODUCTION OUTPUTS
source("../../../z-scripts/create_production_output.R", local = knitr::knit_global())


```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

