---
pagetitle: "Kamino"
output:
  bookdown::gitbook: default
documentclass: book
date: "`r Sys.Date()`"
---

```{r, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

```

<div class="activity">
CHARTS  
</div>

# Divergent Bar Chart
## Visualize Differences

Divergent Bar Charts are great for showcasing disagreement, difference, discrepancy, and debate of opinions. It allows comparisons between different categories. The chart plots the categories on a divergent line. The divergent line can be zero or show a point that separates the two dimension member.It is also very common to utilize different colors to distinguish either sides of the divergent line. For example, "Agree" can be charted to the right of the divergent line and colored green. Whereas, "Disagree" can be charted to the left of the divergent line and colored red. 

As all bar chart, the length of each bar is proportional to the numerical value assigned, and each bar represents a category. Often divergent bar charts are used to show the frequency of responses in surveys.


