---
title: "Template"
output:
  bookdown::gitbook: default
documentclass: book
date: "`r Sys.Date()`"
---

```{r, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

# Java must be installed as a prerequisite
library(rJava)

library(tidyverse)
library(tidytext)
library(NLP)
library(openNLP)
library(RWeka)

```


## SET PARAMETERS


```{r}

focus_question <- 11
question_language <- "en"

question_list <- read.csv("list-of-questions.csv", header = TRUE, stringsAsFactors = FALSE, encoding="UTF-8")
question_list

question_filter <- filter(question_list, QID == focus_question)
question_filter$Question

```



## INGEST DATA


```{r}

data_file <- paste0("./outputs/q-", focus_question, "-lang.csv")

corpus_csv <- read.csv(data_file, header = TRUE, stringsAsFactors = FALSE, encoding="UTF-8")

# Filter english
corpus_csv <- filter(corpus_csv, cld2 == question_language)
corpus_csv

```


## PREPARE DATA


```{r, echo=FALSE, message=FALSE}

#read text
text <- corpus_csv$Comment

#convert the character vectors into one character vector
text <- paste(text, collapse = " ")
# print(text)

#converts variable into a string
text <- as.String(text)

```


## LOAD AND RUN MODELS


```{r}

#create annotators for words and sentences
word_ann <- Maxent_Word_Token_Annotator()
sent_ann <- Maxent_Sent_Token_Annotator()
pos_tag_ann <- Maxent_POS_Tag_Annotator()

#creates annotators of kind person, location and organization
organization_ann <- Maxent_Entity_Annotator(kind = "organization")
person_ann <- Maxent_Entity_Annotator(kind = "person")
location_ann <- Maxent_Entity_Annotator(kind = "location")
date_ann <- Maxent_Entity_Annotator(kind = "date")
percentage_ann <- Maxent_Entity_Annotator(kind = "percentage")
money_ann <- Maxent_Entity_Annotator(kind = "money")

#holds annotators in the order to be applied
pipeline <- list(sent_ann,
                 word_ann,
                 pos_tag_ann,
                 person_ann,
                 location_ann,
                 organization_ann,
                 date_ann,
                 percentage_ann,
                 money_ann)

annotated_text <- annotate(as.String(text), pipeline)


```


## NER


```{r, echo=FALSE, message=FALSE}

# NER

k <- sapply(annotated_text$features, `[[`, "kind")
organizations <- text[annotated_text[k == "organization"]]
people <- text[annotated_text[k == "person"]]
locations <- text[annotated_text[k == "location"]]
date <- text[annotated_text[k == "date"]]
percentage <- text[annotated_text[k == "percentage"]]
money <- text[annotated_text[k == "money"]]

organizations <- as.data.frame(organizations)
names(organizations)[1] <- "word"
organizations$ner <- "ORGANIZATION"
organizations

people <- as.data.frame(people)
names(people)[1] <- "word"
people$ner <- "PEOPLE"
people

locations <- as.data.frame(locations)
names(locations)[1] <- "word"
locations$ner <- "LOCATION"
locations

date <- as.data.frame(date)
names(date)[1] <- "word"
date$ner <- "DATE"
date

percentage <- as.data.frame(percentage)
names(percentage)[1] <- "word"
percentage$ner <- "PERCENTAGE"
percentage

#money <- as.data.frame(money)
#names(money)[1] <- "word"
#money$ner <- "MONEY"
#money

ner_df <- rbind(organizations, people, locations, date, percentage, money)
ner_df


```

## WRITE RESULT

```{r}

ner_summary <- ner_df %>% count(word, ner, sort = TRUE)
ner_summary

ner_file <- paste0("./outputs/named-entity-recognition/q-", focus_question, "-ner.csv")
write.csv(ner_summary, ner_file, row.names = FALSE)

```


