---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggiraph)

library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS
</div>

# Marimekko
## Capital cities would you live there

***

# Load data
## capital-cities-would-you-live-there


```{r, echo=FALSE}

# Create dataset
df = read.csv("archetypes/capital-cities/capital-cities-would-you-live-there.csv", header = TRUE)
df

```

# Prepare data


```{r, echo=FALSE}

#df_top <- df %>% slice_max(Population, n = 15)
#df_top

df_top <- sample_n(df, 15)

df_top$xmax <- cumsum(df_top$Population)
df_top$xmin <- df_top$xmax - df_top$Population
df_top$xlabel <- (df_top$xmax + df_top$xmin)/2
df_top$label <- paste(as.character(round(df_top$Measure, digits=0)),"%")

```

# Plot

```{r, echo=FALSE, fig.width=12, fig.height=10, out.width = "95%"}

theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
  plot.margin = unit(c(0, 0, 1.25, 0), "in")
)

v1 <-ggplot(df_top) +
    geom_rect(aes(ymin = 0, ymax = Measure, xmin = xmin, xmax = xmax, fill = Country), color = "white", alpha = 0.5) + 
    geom_text(aes(x = xlabel, y = Measure, label = label, vjust = -1), position = "identity", color = "black", size = 3 ) +
    geom_text(aes(x = xlabel, y = 2, label = Population, vjust = 0), position = "identity", color = "black", size = 3 ) +
    geom_text(aes(x = xlabel, y = 0, label = City), hjust = "right", vjust = 1.5, position = "identity", color = "black", size = 3.5, angle = 45 ) +
    geom_hline(yintercept = 10) +
    coord_cartesian(clip="off") +
    theme(plot.title = element_text(size = rel(2)), panel.background = element_rect(fill = "white", colour = "grey50")) +
    theme_opts

girafe(ggobj = v1, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```


## Save output

```{r, echo=FALSE}

# ggsave(filename = "capital-cities-would-you-live-there.svg", plot = v1, width=12, height=6)

```


# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case

Source: <a href="https://www.economist.com/graphic-detail/2019/08/23/which-countries-dominate-the-worlds-dinner-tables"> Which countries dominate the world’s dinner tables?</a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


