---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: hide
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggiraph)

library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS
</div>

# Marimekko
## Internet Penetration by Region

***

# Load data


```{r, echo=TRUE}

# Create dataset
df = read.csv("archetypes/internet-penetration-by-region/internet-penetration-by-region.csv", header = TRUE)
df

```

# Prepare data

```{r, echo=TRUE}

df$xmax <- cumsum(df$Population_Percent_of_World)
df$xmin <- df$xmax - df$Population_Percent_of_World
df$xlabel <- (df$xmax + df$xmin)/2
df$label <- paste(as.character(df$Penetration_Rate*100),"%")
data<-df %>% rename(Regions=World_Regions)
data

```

# Plot

```{r, echo=TRUE, fig.width=12, fig.height=8, out.width = "85%"}

theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background=element_rect(fill="white", colour="white"),
  panel.border = element_blank(),
  plot.background = element_blank(),
  plot.margin = unit(c(0, 0, 1, 0), "in")
)

v1 <-ggplot(data) +
    geom_rect(aes(ymin = 0, ymax = Penetration_Rate, xmin = xmin, xmax = xmax, fill = Regions), color = "white", alpha = 0.5) + 
    geom_text(aes(x = xlabel, y = Penetration_Rate, label = label, vjust = -1), position = "identity", color = "black", size = 3 ) +
    geom_text(aes(x = xlabel, y = 0, label = Regions), hjust = "right", vjust = 0.5, position = "identity", color = "black", size = 3.5, angle = 45 ) +
    geom_hline(yintercept = 0.6) +
    coord_cartesian(clip="off") +
    theme(plot.title = element_text(size = rel(2)), panel.background = element_rect(fill = "white", colour = "grey50")) +
    theme_opts

girafe(ggobj = v1, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```


# Save plot

```{r, echo=TRUE}

# ggsave(filename = "internet-penetration-by-region.svg", plot = v1, width=12, height=8)

```


# Exercises and practice
## Knime and R practice solutions



# References
## The citations and data sources used for this case



```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

# cleanbib()
# read.bibtex(file = "./citations.bib")

```


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```


