---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["styles/kamino.css"]
    df_print: paged
    mathjax: NULL
    code_folding: hide
---

```{r setup, include = FALSE, results = "hide"}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(sf)
library(geojsonio)
library(ggplot2)
library(ggiraph)

```



```{r, message = FALSE, warning = FALSE, echo = FALSE, results = "hide"}

# Load map sources
# ++++++++++++++++++++

adm0 <- st_read("map-sources/eth_admbnda_adm0_csa_bofed_20201008.geojson")
adm1 <- st_read("map-sources/eth_admbnda_adm1_csa_bofed_20201008.geojson")
adm2 <- st_read("map-sources/eth_admbnda_adm2_csa_bofed_20201008.geojson")

waterways_lines <- st_read("map-sources/hotosm_eth_waterways_lines.geojson")
waterways_polygons <- st_read("map-sources/hotosm_eth_waterways_polygons.geojson")

# roads_lines <- st_read("map-sources/hotosm_eth_roads_lines.geojson")

airports = read.csv("map-sources/hotosm_eth_airports_points.csv", header = TRUE, stringsAsFactors = FALSE)
sea_ports = read.csv("map-sources/hotosm_eth_sea_ports_points.csv", header = TRUE, stringsAsFactors = FALSE)

head(as.data.frame(adm0))
head(as.data.frame(adm1))
head(as.data.frame(adm2))
# head(as.data.frame(roads_lines))
head(airports)
head(sea_ports)

```


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=12, out.width = "100%"}

# theme parameters
theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # panel.background = element_blank(),
  panel.background = element_rect(fill = "#ffffff"),
  panel.border = element_blank(),
  # plot.background = element_blank(),
  plot.background = element_rect(fill = "#ffffff")
)

transparent_fill <- rgb(0, 0, 0, max = 255, alpha = 0, names = "transparent")

# In order of layer placement top -> down
v1 = ggplot() + 
  # geom_sf( data = roads_lines, color = "#CAD0D8", fill = "#CAD0D8", size = 0.3 ) +
  geom_sf(data = waterways_polygons, color="#7CB3DB", fill = "#7CB3DB", size=0.3) +
  geom_sf(data = waterways_lines, color="#d4f1f9", size=0.3) +
  geom_sf(data = adm0, color="#333333", fill = transparent_fill, size=2.0) +
  geom_sf(data = adm1, color="#333333", fill = transparent_fill, size=1.0) +
  geom_sf(data = adm2, color="#333333", fill = transparent_fill, size=0.5) +
  geom_point( data = sea_ports, aes(x = X, y = Y), size = 2 , color = "red", alpha = 1.0 ) +
  geom_point( data = airports, aes(x = X, y = Y), size = 2 , color = "orange", alpha = 1.0 ) +
  scale_x_continuous() +
  scale_y_continuous() +
  coord_sf() +
  theme_bw() +
  labs(x = NULL, # Longitude
       y = NULL, # Latitude
       title = NULL, 
       subtitle = NULL) +
  theme_opts

# v1

girafe( ggobj = v1, width_svg = 12, height_svg = 8, options = list( opts_sizing(rescale = TRUE, width = 0.9) ))

```




```{r, message = FALSE, warning = FALSE, echo = FALSE}

ggsave(filename = "assets/23-eth-transportation.svg", plot = v1, width=12, height=12)

```

