---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["styles/kamino.css"]
    df_print: paged
    mathjax: NULL
    code_folding: hide
---

```{r setup, include = FALSE, results = "hide"}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(sf)
library(geojsonio)
library(ggplot2)
library(ggiraph)

```



```{r, message = FALSE, warning = FALSE, echo = FALSE, results = "hide"}

# Load map sources
# Shape files and data
# ++++++++++++++++++++
# borders, adm0
# borders, adm1
# borders, adm2
# ++++++++++++++++++++
# final_southern_sudan_roads_version01
# hotosm_ssd_railways_lines_shp
# hotosm_ssd_railways_points_shp
# hotosm_ssd_railways_polygons_shp
# ssd_trs_roads_osm
# ssd_trs_streets_osm
# airports
# ++++++++++++++++++++

# Borders
state_boundaries <- st_read("map-sources/geojson/ss-state.geojson")
county <- st_read("map-sources/geojson/ss-county.geojson")
abeyi <- st_read("map-sources/geojson/ss-abeyi.geojson")

# final_southern_sudan_roads_version01
roads <- st_read("map-sources/transportation/final_southern_sudan_roads_version01/Final_Southern_Sudan_Roads_Version01.shp")

# hotosm_ssd_railways_lines_shp
railways_lines <- st_read("map-sources/transportation/hotosm_ssd_railways_lines_shp/hotosm_ssd_railways_lines.shp")

# hotosm_ssd_railways_points_shp
# railways_points <- st_read("map-sources/transportation/hotosm_ssd_railways_points_shp/hotosm_ssd_railways_points.shp")

# hotosm_ssd_railways_polygons_shp
# railways_polygons <- st_read("map-sources/transportation/hotosm_ssd_railways_polygons_shp/hotosm_ssd_railways_polygons.shp")

# ssd_trs_roads_osm
roads_osm <- st_read("map-sources/transportation/ssd_trs_roads_osm/ssd_trs_roads_osm.shp")

# ssd_trs_streets_osm
# streets_osm <- st_read("map-sources/transportation/ssd_trs_streets_osm/ssd_trs_streets_osm.shp")

# airports
airports = read.csv("map-sources/transportation/ssd-airports.csv", header = TRUE, stringsAsFactors = FALSE)

head(as.data.frame(roads))
#head(as.data.frame(railways_lines))
#head(as.data.frame(railways_points))
#head(as.data.frame(railways_polygons))
#head(as.data.frame(roads_osm))
#head(as.data.frame(streets_osm))
head(airports)

roads_df <- st_as_sf(roads)
#borehole <- waterpoints_df %>% filter(Source_Typ=="Borehole")
#borehole

```




```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=12, out.width = "100%"}

# Plot by layer
# adm0, adm1, adm2

# theme parameters
theme_opts <- theme(
  legend.position = "none",
  legend.title = element_blank(),
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  axis.title = element_blank(),
  panel.grid = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # panel.background = element_blank(),
  panel.background = element_rect(fill = "#ffffff"),
  panel.border = element_blank(),
  # plot.background = element_blank(),
  plot.background = element_rect(fill = "#ffffff")
)

transparent_fill <- rgb(0, 0, 0, max = 255, alpha = 0, names = "transparent")

# In order of layer placement top -> down
v1 = ggplot() + 
  # geom_sf( data = roads, color = "#CAD0D8", fill = "#CAD0D8", size = 0.3 ) +
  # geom_sf( data = roads_osm, color = "#CAD0D8", fill = "#CAD0D8", size = 0.3 ) +
  #geom_sf( data = streets_osm, color = "#CAD0D8", fill = "#CAD0D8", size = 0.3 ) +
  geom_sf( data = railways_lines, color = "blue", fill = "blue", size = 0.8 ) +
  geom_point( data = airports, aes(x = longitude_deg, y = latitude_deg), size = 2 , color = "red", alpha = 0.8 ) +
  geom_sf(data = state_boundaries, color="#333333", fill = transparent_fill, size=1.0) +
  geom_sf(data = county, color="#333333", fill = transparent_fill, size=0.5) +
  geom_sf(data = abeyi, color="#333333", fill = transparent_fill, size=0.5, linetype = "dashed") +
  scale_x_continuous() +
  scale_y_continuous() +
  coord_sf() +
  theme_bw() +
  labs(x = NULL, # Longitude
       y = NULL, # Latitude
       title = NULL, 
       subtitle = NULL) +
  theme_opts

# v1

girafe( ggobj = v1, width_svg = 12, height_svg = 8, options = list( opts_sizing(rescale = TRUE, width = 0.9) ))

```



```{r, message = FALSE, warning = FALSE, echo = FALSE}

ggsave(filename = "assets/3-ssd-transportation.svg", plot = v1, width=12, height=12)

```

