---
pagetitle: "Candlestick"
output: 
  html_document:
    theme: flatly
    code_folding: show
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)

options(scipen=999)  # turn-off scientific notation like 1e+48
library(tidyquant)
library(dplyr)
library(ggplot2)
library(scales)

```

### Candlestick : S&P 500

<p>A candlestick chart is a style of financial chart used to describe price movements of a security, derivative, or currency. Each "candlestick" typically shows one day, thus a one-month chart may show the 20 trading days as 20 candlesticks.[1] Candlestick charts can also be built using intervals shorter or longer than one day.</p>

```{r, echo=FALSE}
df = read.csv("../archetypes/^GSPC.csv", header = TRUE, stringsAsFactors = FALSE)

df$Date <- as.Date(df$Date, format = "%Y-%m-%d")

df

```


```{r, echo=FALSE, fig.width=10.5, fig.height=7.5}

candlestick = ggplot(df, aes(x = Date, y = Close)) +
    geom_candlestick(aes(open = Open, high = High, low = Low, close = Close)) +
    geom_ma(color = "darkgreen") +
    coord_x_date() +
    scale_x_date(date_breaks = '1 month', labels = date_format("%m-%Y")) +
    theme_bw()

candlestick

```

```{r, echo=FALSE}
ggsave(filename = "GSPC-candlestick.svg", plot = candlestick, width=13.33, height=7.5)
```

