---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    #code_folding: show
    include:
     in_header: "../../../z-assemblers/fragments/header.html"
     after_body: "../../../z-assemblers/fragments/footer.html"
    #self_contained: false
    #lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48


library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS  
</div>

# Ranking Bar Plots
## Ordering Bars in ggplot2


Bar charts are very helpful for displaying the frequencies of different categories of data. Sometimes, it can be useful to order and rank the bar plots in a way it matches with the story we're telling. By default, while creating a bar plot with categorical labels, ggplot will order the plot alphabetically. In that case, there are a few ways to rank the the bar plot:

* __Using factor() levels__ : By converting data into a factor, we can order bars manually using the levels
* __Using factor()__ : We can order bars in numerically ascending/descending order using factor() appropriately
* __Using reorder()__ : We can also utilize the reorder() function to rank bars numerically. For Descending order, we use reorder(x,y). For Ascending order, we use reorder(x,-y).

Bar Charts can be ranked whether it is in a horizontal format or a vertical format. 


```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

