---
pagetitle: "World Electricity Production"
output:
  html_document:
    theme: lumen
    css: "../../../z-assemblers/assets/styles/content.css"
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: ["../../../z-assemblers/fragments/google-analytics.html", "../../../z-assemblers/fragments/header.html"]
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: "vendor"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(tidyverse)
library(factoextra)
library(ggplot2)
library(ggiraph)


library(showtext)
## Loading Google fonts (https://fonts.google.com/)
font_add_google("Inconsolata", "inconsolata")
# turn on showtext
showtext_auto()

```

<div class="activity">
CHARTS  
</div>

# Human Development Index
## Biplot

> Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...\
--- Lorem Ipsum\

***

# Ingest and wrangle data


```{r, echo=FALSE}

src <- read.csv('archetypes/gapminder.csv', encoding = "UTF-8")
src


# Select relevant fields
src_select <- src %>% select(country, gdp, life_expectancy, pop )
src_select


# The pca function can only take numeric values,
# so we convert Country column to be rownames
df <- column_to_rownames(src_select, var = "country")

# Use only complete cases
df <- df[complete.cases(df), ]
df


```

# Fit a principal components model

```{r, echo=FALSE}

# fit a principal components model
df_pca <- prcomp(x = df, 
              center = TRUE, 
              scale = TRUE)
df_pca

```

# Plot

```{r, echo=FALSE, fig.width=13, fig.height=7, out.width="100%"}

# fviz_pca function produces a ggplot2 graph.
gm_biplot <- fviz_pca(df_pca,  repel = TRUE,  labelsize = 3) + 
  theme_bw() +
  labs(title = "HDI Biplot")

# Draw plot
girafe(ggobj = gm_biplot, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))


```
 
 
```{r}

# Save plot to svg file
# ggsave(filename = "assets/mtcars_biplot.svg", plot = mtcars_biplot, width=24.5, height=13)

```
 
 
# References
## The citations and data sources used for this case

[Gapminder](http://gapminder.org)

```{r generateBibliography, echo=FALSE, message=FALSE, warning=FALSE}

#cleanbib()
#options("citation_format" = "pandoc")
#read.bibtex(file = "citations/average-working-hours-of-children.bib")

```



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```