---
title: "Keyword In Context (KWIC)"
output: 
  html_document:
    theme: flatly
    df_print: paged
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48
# set.seed(100)

library(tidyverse)
library(tidytext)
library(dplyr)
library(tm)
library(quanteda)
library(corpustools)
library(igraph)

library("quanteda.textplots")
library("quanteda.textstats")

library(ggpubr)

```




```{r, echo=FALSE, message=FALSE}

## SET PARAMETERS

focus_question <- 11
question_language <- "en"

question_list <- read.csv("list-of-questions.csv", header = TRUE, stringsAsFactors = FALSE, encoding="UTF-8")
#question_list

question_filter <- filter(question_list, QID == focus_question)
question_filter$Question

q_keyword <- question_filter$Keyword

message <- paste0("Keyword used:", q_keyword)
message

```


```{r, echo=FALSE, message=FALSE}

## INGEST DATA

data_file <- paste0("./outputs/q-", focus_question, "-lang.csv")

corpus_csv <- read.csv(data_file, header = TRUE, stringsAsFactors = FALSE, encoding="UTF-8")

# Filter english
corpus_csv <- filter(corpus_csv, cld2 == question_language)
#corpus_csv

```

## SINGLE WORD ROOT

```{r, echo=FALSE, message=FALSE, rows.print=20}

## QUANTEDA

corpus_txt <- corpus(corpus_csv$Comment)
keyword <- paste0(q_keyword, '*')

kwic_keyword <- kwic(corpus_txt, pattern = keyword, valuetype = "regex")
#names(kwic_keyword)

kwic_keyword <- data.frame(kwic_keyword, stringsAsFactors=F)
# kwic_keyword

vars <- c("pre", "keyword", "post")
kwic_select <- kwic_keyword  %>% select(one_of(vars))
# kwic_select

kwic_select$kwic <- paste0( kwic_select$pre, " | ", kwic_select$keyword, " | ", kwic_select$post )
kwic_print <- kwic_select  %>% select(kwic)


DT::datatable(kwic_print)


```

## TWO WORD ROOT


```{r, echo=FALSE, message=FALSE, rows.print=20}

## CORPUSTOOLS

# http://htmlpreview.github.io/?https://github.com/kasperwelbers/corpustools/blob/master/vignettes/corpustools.html

tc = create_tcorpus(corpus_csv, doc_column = 'row', text_columns = 'Comment')
tc_kwic <- get_kwic(tc, query = 'tolerate* AND happen*', n = 20)

tc_kwic_print <- tc_kwic %>% select(kwic)
#tc_kwic_print

DT::datatable(tc_kwic_print)


```

