---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo = FALSE)
options(scipen = 999) ## To disable scientific notation

# Clear environment and memory
rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.

library(dplyr)
library(magrittr)
library(ggplot2)
require(ggrepel)
library(scales)
library(ggiraph)

library(knitcitations)
library(bibtex)

```

<div class="activity">
TEMPORALS
</div>

# Slope Plot
## Maternal Mortality

***

## Load data [Ingest]

```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Load csv data file
maternal_mortality_df = read.csv("archetypes/maternal-mortality-slope-chart.csv", header = TRUE, stringsAsFactors = FALSE)
maternal_mortality_df

```


## Prepare data [Wrangle]


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Filter for year and continent
maternal_mortality_df <- maternal_mortality_df %>%
  filter(Year %in% c(2000, 2005, 2010, 2015) &
           Continent %in% c("Oceania", "World"))
# Create ordered factor for year
maternal_mortality_df$Year <- factor(maternal_mortality_df$Year, ordered = TRUE, levels = c("2000", "2005", "2010", "2015"))
maternal_mortality_df

```


## Plot [ Views / Temporals ]


```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide', fig.width=12, fig.height=8, , fig.align='center', out.width="100%"}

color_palette <- c("Kiribati" = "#cccccb", 
                   "Papua New Guinea" = "#cccccb", 
                   "Nauru" = "#cccccb", 
                   "Tuvalu" = "#cccccb",
                   "Micronesia" = "#cccccb",
                   "Marshall Islands" = "#cccccb",
                   "Vanuatu" = "#cccccb",
                   "Solomon Islands" = "#cccccb",
                   "Palau" = "#cccccb",
                   "Samoa" = "#cccccb",
                   "Fiji" = "#cccccb",
                   "Tonga" = "#d8472b",
                   "New Zealand" = "#cccccb",
                   "Australia" = "#cccccb",
                   "World" = "#7dbfe6")

slope_specs <- list(  
  # move the x axis labels up top
  scale_x_discrete(position = "top"),
  theme_bw(),
  # Format tweaks
  # Remove the legend
  theme(legend.position = "none"),
  # Remove the panel border
  theme(panel.border     = element_blank()),
  # Remove just about everything from the y axis
  theme(axis.title.y     = element_blank()),
  theme(axis.text.y      = element_blank()),
  theme(panel.grid.major.y = element_blank()),
  theme(panel.grid.minor.y = element_blank()),
  # Remove a few things from the x axis and increase font size
  theme(axis.title.x     = element_blank()),
  theme(panel.grid.major.x = element_blank()),
  theme(axis.text.x.top      = element_text(size=12)),
  # Remove x & y tick marks
  theme(axis.ticks       = element_blank()),
  # Format title & subtitle
  theme(plot.title       = element_text(size=14, face = "bold")),
  theme(plot.subtitle    = element_text())
)

maternal_mortality = ggplot(data = maternal_mortality_df, aes(x = Year, y = Maternal_Mortality_Ratio, group = Entity)) +
  geom_line(aes(color = Entity), size = 0.5, alpha = 1) +
  geom_text_repel(data = maternal_mortality_df %>% filter(Year == "2000"), 
                  aes(label = paste0(Entity)) , 
                  force = 1,
                  hjust = "left", 
                  fontface = "bold", 
                  size = 2.5, 
                  nudge_x = -.5, 
                  direction = "y",
                  segment.color = "gray") +
  geom_text_repel(data = maternal_mortality_df %>% filter(Year == "2015"), 
                  aes(label = paste0(Entity)), 
                  force = 1,
                  hjust = "right", 
                  fontface = "bold", 
                  size = 2.5, 
                  nudge_x = .5, 
                  direction = "y",
                  segment.color = "gray") +
  geom_point(aes(fill = Entity), shape = 21, color="white", size = 2, stroke = 0.75, alpha = 1) +
  # geom_text(aes(label = Maternal_Mortality_Ratio), color="black", size = 2.5, alpha = 1) +
  geom_text_repel(aes(label = Maternal_Mortality_Ratio), color="black", size = 2.5, alpha = 1,
                  force = 1,
                  hjust = "center", 
                  #fontface = "bold", 
                  size = 2.0, 
                  # nudge_x = 0, 
                  direction = "y",
                  segment.color = "gray") +
  scale_fill_manual(values = color_palette) +
  scale_color_manual(values = color_palette) +
  slope_specs +
  labs(
    title = "Maternal Mortality by Country",
    subtitle = "Oceania, Maternal deaths per 100,000 live births.",
    caption = "source: Our World in Data"
  )

girafe(ggobj = maternal_mortality, width_svg = 13, height_svg = 7,
       options = list(opts_sizing(rescale = TRUE, width = 1.0)))

```




```{r, message=FALSE, warning=FALSE, echo=TRUE, class.source = 'fold-hide'}

# Save plot to svg file
# width and height defined for kamino aspect ratio
# ggsave(filename = "maternal_mortality.svg", plot = maternal_mortality, width=13.33, height=7.5)

```



# References
## The citations and data sources used for this case can be found here:

<a href="https://ourworldindata.org/grapher/maternal-mortality-slope-chart?time=1990..latest&country=ARG~BOL~BRA~ECU~GUY~URY~VEN~PRY~PER~SUR~CHL~COL" target="_blank">Maternal Mortality</a>

```{r generateBibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

 cleanbib()
 read.bibtex(file = "citations/maternal-mortality.bib")

```




```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

