---
pagetitle: "Kamino"
output: 
  html_document:
    theme: lumen
    css: ["../../../z-assemblers/assets/styles/content/kamino.css", "../../../z-assemblers/assets/icons/line-awesome/css/line-awesome.css"]
    df_print: paged
    mathjax: NULL
    code_folding: show
    include:
      in_header: "../../../z-assemblers/fragments/header.html"
      after_body: "../../../z-assemblers/fragments/footer.html"
    self_contained: false
    lib_dir: libs
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message=FALSE, warning=FALSE, echo=FALSE)
options(scipen=999)  # turn-off scientific notation like 1e+48


library(knitcitations)
library(bibtex)

```

<div class="activity">
CHARTS  
</div>

# Parliament Plot
## Visualize election results as points in the architectural layout of the legislative chamber

ggparliament is a ggplot2 extension for creating parliament plots. This R package allows users to plot different styles of legislatures. They are:

* semicircle layouts
* horseshoe parliaments
* opposing bench-style parliaments
* the classroom layout
* a circular parliament.

To plot a parliament chart in ggparliament, we start with a data frame containing the number of seats per political party. This package comes with recent election results from the UK, Australia, the United Sates, Russia, and Germany. election_data also provides party colour, abbreviated and full versions of the party name, as well as election returns over several election cycles.



```{js, message=FALSE, warning=FALSE, echo=FALSE}

// Must be included to position footer
$(function() {
  $('.main-container').after($('.footer'));
})

```

